<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi2\JsonSchema\Model;

use Jane\Component\OpenApi2\JsonSchema\Runtime\AdditionalAndPatternProperties;
use Jane\Component\OpenApi2\JsonSchema\Runtime\AdditionalPropertiesInterface;

class ApiKeySecurity implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    public ?string $type;
    public ?string $name;
    public ?string $in;
    public ?string $description;

    public function definedProperties(): array
    {
        return ['type' => 'type', 'name' => 'name', 'in' => 'in', 'description' => 'description'];
    }
}
