<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi2\JsonSchema\Model;

use Jane\Component\OpenApi2\JsonSchema\Runtime\AdditionalAndPatternProperties;
use Jane\Component\OpenApi2\JsonSchema\Runtime\AdditionalPropertiesInterface;

class BodyParameter implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    /**
     * A brief description of the parameter. This could contain examples of use.  GitHub Flavored Markdown is allowed.
     */
    public ?string $description;
    /**
     * The name of the parameter.
     */
    public ?string $name;
    /**
     * Determines the location of the parameter.
     */
    public ?string $in;
    /**
     * Determines whether or not this parameter is required or optional.
     */
    public ?bool $required = false;
    /**
     * @var Schema|JsonReference|null
     */
    public $schema;

    public function definedProperties(): array
    {
        return ['description' => 'description', 'name' => 'name', 'in' => 'in', 'required' => 'required', 'schema' => 'schema'];
    }
}
