<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi2\JsonSchema\Model;

use Jane\Component\OpenApi2\JsonSchema\Runtime\AdditionalAndPatternProperties;
use Jane\Component\OpenApi2\JsonSchema\Runtime\AdditionalPropertiesInterface;

class Response implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    public ?string $description;
    /**
     * @var Schema|FileSchema|null
     */
    public $schema;
    /**
     * @var array<string, Header>|null
     */
    public ?iterable $headers;
    /**
     * @var array<string, mixed>|null
     */
    public ?iterable $examples;

    public function definedProperties(): array
    {
        return ['description' => 'description', 'schema' => 'schema', 'headers' => 'headers', 'examples' => 'examples'];
    }
}
