<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi2\Model;

class Contact extends \ArrayObject
{
    /**
     * The identifying name of the contact person/organization.
     *
     * @var string
     */
    protected $name;
    /**
     * The URL pointing to the contact information.
     *
     * @var string
     */
    protected $url;
    /**
     * The email address of the contact person/organization.
     *
     * @var string
     */
    protected $email;

    /**
     * The identifying name of the contact person/organization.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * The identifying name of the contact person/organization.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * The URL pointing to the contact information.
     *
     * @return string
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * The URL pointing to the contact information.
     *
     * @param string $url
     *
     * @return self
     */
    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    /**
     * The email address of the contact person/organization.
     *
     * @return string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * The email address of the contact person/organization.
     *
     * @param string $email
     *
     * @return self
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }
}
