<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi2\Model;

class JsonReference
{
    /**
     * @var string
     */
    protected $dollarRef;

    /**
     * @return string
     */
    public function getDollarRef(): ?string
    {
        return $this->dollarRef;
    }

    /**
     * @param string $dollarRef
     *
     * @return self
     */
    public function setDollarRef(?string $dollarRef): self
    {
        $this->dollarRef = $dollarRef;

        return $this;
    }
}
