<?php

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected\Normalizer;

class NormalizerFactory
{
    public static function create()
    {
        $normalizers   = [];
        $normalizers[] = new \Symfony\Component\Serializer\Normalizer\ArrayDenormalizer();
        $normalizers[] = new FooNormalizer();
        $normalizers[] = new BarNormalizer();
        $normalizers[] = new TestGetBodyNormalizer();
        $normalizers[] = new TestGetBodyBazNormalizer();
        $normalizers[] = new TestPostBodyNormalizer();

        return $normalizers;
    }
}
