<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi31\JsonSchema\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use Jane\Component\OpenApi31\JsonSchema\Runtime\Normalizer\CheckArray;
use Jane\Component\OpenApi31\JsonSchema\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class EncodingNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Jane\Component\OpenApi31\JsonSchema\Model\Encoding::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return $data instanceof \Jane\Component\OpenApi31\JsonSchema\Model\Encoding;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \Jane\Component\OpenApi31\JsonSchema\Model\Encoding();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref']) && !isset($data['type']) && !isset($data['properties']) && !isset($data['allOf'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        if (\array_key_exists('explode', $data) && \is_int($data['explode'])) {
            $data['explode'] = (bool) $data['explode'];
        }
        if (\array_key_exists('allowReserved', $data) && \is_int($data['allowReserved'])) {
            $data['allowReserved'] = (bool) $data['allowReserved'];
        }
        if (\array_key_exists('contentType', $data) && $data['contentType'] !== null) {
            $object->contentType = $data['contentType'];
        } elseif (\array_key_exists('contentType', $data) && $data['contentType'] === null) {
            $object->contentType = null;
        }
        if (\array_key_exists('headers', $data) && $data['headers'] !== null) {
            $values = new \Jane\Component\OpenApi31\JsonSchema\Runtime\JsonObject();
            foreach ($data['headers'] as $key => $value) {
                $values[$key] = $value;
            }
            $object->headers = $values;
        } elseif (\array_key_exists('headers', $data) && $data['headers'] === null) {
            $object->headers = null;
        }
        if (\array_key_exists('style', $data) && $data['style'] !== null) {
            $object->style = $data['style'];
        } elseif (\array_key_exists('style', $data) && $data['style'] === null) {
            $object->style = null;
        }
        if (\array_key_exists('explode', $data) && $data['explode'] !== null) {
            $object->explode = $data['explode'];
        } elseif (\array_key_exists('explode', $data) && $data['explode'] === null) {
            $object->explode = null;
        }
        if (\array_key_exists('allowReserved', $data) && $data['allowReserved'] !== null) {
            $object->allowReserved = $data['allowReserved'];
        } elseif (\array_key_exists('allowReserved', $data) && $data['allowReserved'] === null) {
            $object->allowReserved = null;
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if (array_key_exists('contentType', get_object_vars($data)) && null !== ($data->contentType ?? null)) {
            $dataArray['contentType'] = $data->contentType ?? null;
        }
        if (array_key_exists('headers', get_object_vars($data)) && null !== ($data->headers ?? null)) {
            $values = new \Jane\Component\OpenApi31\JsonSchema\Runtime\JsonObject();
            foreach ($data->headers ?? null as $key => $value) {
                $values[$key] = $value;
            }
            $dataArray['headers'] = $values;
        }
        if (array_key_exists('style', get_object_vars($data)) && null !== ($data->style ?? null)) {
            $dataArray['style'] = $data->style ?? null;
        }
        if (array_key_exists('explode', get_object_vars($data)) && null !== ($data->explode ?? null)) {
            $dataArray['explode'] = $data->explode ?? null;
        }
        if (array_key_exists('allowReserved', get_object_vars($data)) && null !== ($data->allowReserved ?? null)) {
            $dataArray['allowReserved'] = $data->allowReserved ?? null;
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Jane\Component\OpenApi31\JsonSchema\Model\Encoding::class => false];
    }
}
