<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi31\JsonSchema\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use Jane\Component\OpenApi31\JsonSchema\Runtime\Normalizer\CheckArray;
use Jane\Component\OpenApi31\JsonSchema\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class OperationNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Jane\Component\OpenApi31\JsonSchema\Model\Operation::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return $data instanceof \Jane\Component\OpenApi31\JsonSchema\Model\Operation;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \Jane\Component\OpenApi31\JsonSchema\Model\Operation();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref']) && !isset($data['type']) && !isset($data['properties']) && !isset($data['allOf'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        if (\array_key_exists('deprecated', $data) && \is_int($data['deprecated'])) {
            $data['deprecated'] = (bool) $data['deprecated'];
        }
        if (\array_key_exists('tags', $data) && $data['tags'] !== null) {
            $values = [];
            foreach ($data['tags'] as $value) {
                $values[] = $value;
            }
            $object->tags = $values;
            unset($data['tags']);
        } elseif (\array_key_exists('tags', $data) && $data['tags'] === null) {
            $object->tags = null;
            unset($data['tags']);
        }
        if (\array_key_exists('summary', $data) && $data['summary'] !== null) {
            $object->summary = $data['summary'];
            unset($data['summary']);
        } elseif (\array_key_exists('summary', $data) && $data['summary'] === null) {
            $object->summary = null;
            unset($data['summary']);
        }
        if (\array_key_exists('description', $data) && $data['description'] !== null) {
            $object->description = $data['description'];
            unset($data['description']);
        } elseif (\array_key_exists('description', $data) && $data['description'] === null) {
            $object->description = null;
            unset($data['description']);
        }
        if (\array_key_exists('externalDocs', $data) && $data['externalDocs'] !== null) {
            $object->externalDocs = $this->denormalizer->denormalize($data['externalDocs'], \Jane\Component\OpenApi31\JsonSchema\Model\ExternalDocumentation::class, 'json', $context);
            unset($data['externalDocs']);
        } elseif (\array_key_exists('externalDocs', $data) && $data['externalDocs'] === null) {
            $object->externalDocs = null;
            unset($data['externalDocs']);
        }
        if (\array_key_exists('operationId', $data) && $data['operationId'] !== null) {
            $object->operationId = $data['operationId'];
            unset($data['operationId']);
        } elseif (\array_key_exists('operationId', $data) && $data['operationId'] === null) {
            $object->operationId = null;
            unset($data['operationId']);
        }
        if (\array_key_exists('parameters', $data) && $data['parameters'] !== null) {
            $values_1 = [];
            foreach ($data['parameters'] as $value_1) {
                $values_1[] = $value_1;
            }
            $object->parameters = $values_1;
            unset($data['parameters']);
        } elseif (\array_key_exists('parameters', $data) && $data['parameters'] === null) {
            $object->parameters = null;
            unset($data['parameters']);
        }
        if (\array_key_exists('requestBody', $data) && $data['requestBody'] !== null) {
            $object->requestBody = $data['requestBody'];
            unset($data['requestBody']);
        } elseif (\array_key_exists('requestBody', $data) && $data['requestBody'] === null) {
            $object->requestBody = null;
            unset($data['requestBody']);
        }
        if (\array_key_exists('responses', $data) && $data['responses'] !== null) {
            $object->responses = $this->denormalizer->denormalize($data['responses'], \Jane\Component\OpenApi31\JsonSchema\Model\Responses::class, 'json', $context);
            unset($data['responses']);
        } elseif (\array_key_exists('responses', $data) && $data['responses'] === null) {
            $object->responses = null;
            unset($data['responses']);
        }
        if (\array_key_exists('callbacks', $data) && $data['callbacks'] !== null) {
            $values_2 = new \Jane\Component\OpenApi31\JsonSchema\Runtime\JsonObject();
            foreach ($data['callbacks'] as $key => $value_2) {
                $values_2[$key] = $value_2;
            }
            $object->callbacks = $values_2;
            unset($data['callbacks']);
        } elseif (\array_key_exists('callbacks', $data) && $data['callbacks'] === null) {
            $object->callbacks = null;
            unset($data['callbacks']);
        }
        if (\array_key_exists('deprecated', $data) && $data['deprecated'] !== null) {
            $object->deprecated = $data['deprecated'];
            unset($data['deprecated']);
        } elseif (\array_key_exists('deprecated', $data) && $data['deprecated'] === null) {
            $object->deprecated = null;
            unset($data['deprecated']);
        }
        if (\array_key_exists('security', $data) && $data['security'] !== null) {
            $values_3 = [];
            foreach ($data['security'] as $value_3) {
                $values_4 = new \Jane\Component\OpenApi31\JsonSchema\Runtime\JsonObject();
                foreach ($value_3 as $key_1 => $value_4) {
                    $values_5 = [];
                    foreach ($value_4 as $value_5) {
                        $values_5[] = $value_5;
                    }
                    $values_4[$key_1] = $values_5;
                }
                $values_3[] = $values_4;
            }
            $object->security = $values_3;
            unset($data['security']);
        } elseif (\array_key_exists('security', $data) && $data['security'] === null) {
            $object->security = null;
            unset($data['security']);
        }
        if (\array_key_exists('servers', $data) && $data['servers'] !== null) {
            $values_6 = [];
            foreach ($data['servers'] as $value_6) {
                $values_6[] = $this->denormalizer->denormalize($value_6, \Jane\Component\OpenApi31\JsonSchema\Model\Server::class, 'json', $context);
            }
            $object->servers = $values_6;
            unset($data['servers']);
        } elseif (\array_key_exists('servers', $data) && $data['servers'] === null) {
            $object->servers = null;
            unset($data['servers']);
        }
        foreach ($data as $key_2 => $value_7) {
            if (preg_match('/^x-/', (string) $key_2)) {
                $object[$key_2] = $value_7;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if (array_key_exists('tags', get_object_vars($data)) && null !== ($data->tags ?? null)) {
            $values = [];
            foreach ($data->tags ?? null as $value) {
                $values[] = $value;
            }
            $dataArray['tags'] = $values;
        }
        if (array_key_exists('summary', get_object_vars($data)) && null !== ($data->summary ?? null)) {
            $dataArray['summary'] = $data->summary ?? null;
        }
        if (array_key_exists('description', get_object_vars($data)) && null !== ($data->description ?? null)) {
            $dataArray['description'] = $data->description ?? null;
        }
        if (array_key_exists('externalDocs', get_object_vars($data)) && null !== ($data->externalDocs ?? null)) {
            $dataArray['externalDocs'] = ($data->externalDocs ?? null) === null ? null : new \Jane\Component\OpenApi31\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($data->externalDocs ?? null, 'json', $context));
        }
        if (array_key_exists('operationId', get_object_vars($data)) && null !== ($data->operationId ?? null)) {
            $dataArray['operationId'] = $data->operationId ?? null;
        }
        if (array_key_exists('parameters', get_object_vars($data)) && null !== ($data->parameters ?? null)) {
            $values_1 = [];
            foreach ($data->parameters ?? null as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['parameters'] = $values_1;
        }
        if (array_key_exists('requestBody', get_object_vars($data)) && null !== ($data->requestBody ?? null)) {
            $dataArray['requestBody'] = $data->requestBody ?? null;
        }
        if (array_key_exists('responses', get_object_vars($data)) && null !== ($data->responses ?? null)) {
            $dataArray['responses'] = ($data->responses ?? null) === null ? null : new \Jane\Component\OpenApi31\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($data->responses ?? null, 'json', $context));
        }
        if (array_key_exists('callbacks', get_object_vars($data)) && null !== ($data->callbacks ?? null)) {
            $values_2 = new \Jane\Component\OpenApi31\JsonSchema\Runtime\JsonObject();
            foreach ($data->callbacks ?? null as $key => $value_2) {
                $values_2[$key] = $value_2;
            }
            $dataArray['callbacks'] = $values_2;
        }
        if (array_key_exists('deprecated', get_object_vars($data)) && null !== ($data->deprecated ?? null)) {
            $dataArray['deprecated'] = $data->deprecated ?? null;
        }
        if (array_key_exists('security', get_object_vars($data)) && null !== ($data->security ?? null)) {
            $values_3 = [];
            foreach ($data->security ?? null as $value_3) {
                $values_4 = new \Jane\Component\OpenApi31\JsonSchema\Runtime\JsonObject();
                foreach ($value_3 as $key_1 => $value_4) {
                    $values_5 = [];
                    foreach ($value_4 as $value_5) {
                        $values_5[] = $value_5;
                    }
                    $values_4[$key_1] = $values_5;
                }
                $values_3[] = $values_4;
            }
            $dataArray['security'] = $values_3;
        }
        if (array_key_exists('servers', get_object_vars($data)) && null !== ($data->servers ?? null)) {
            $values_6 = [];
            foreach ($data->servers ?? null as $value_6) {
                $values_6[] = $value_6 === null ? null : new \Jane\Component\OpenApi31\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($value_6, 'json', $context));
            }
            $dataArray['servers'] = $values_6;
        }
        foreach ($data->additionalPropertyEntries() as $key_2 => $value_7) {
            if (preg_match('/^x-/', (string) $key_2)) {
                $dataArray[$key_2] = $value_7;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Jane\Component\OpenApi31\JsonSchema\Model\Operation::class => false];
    }
}
