<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected\Normalizer;

class NormalizerFactory
{
    public static function create()
    {
        $normalizers = [];
        $normalizers[] = new \Symfony\Component\Serializer\Normalizer\ArrayDenormalizer();
        $normalizers[] = new OrderNormalizer();
        $normalizers[] = new UserNormalizer();
        $normalizers[] = new CategoryNormalizer();
        $normalizers[] = new TagNormalizer();
        $normalizers[] = new PetNormalizer();
        $normalizers[] = new ApiResponseNormalizer();

        return $normalizers;
    }
}
