<?php

namespace Jane\Component\OpenApi3\Tests\Expected\Issue770\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use Jane\Component\OpenApi3\Tests\Expected\Issue770\Runtime\Normalizer\CheckArray;
use Jane\Component\OpenApi3\Tests\Expected\Issue770\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
class IdentityCreateIdentityGuestPassNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Jane\Component\OpenApi3\Tests\Expected\Issue770\Model\IdentityCreateIdentityGuestPass::class;
    }
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Jane\Component\OpenApi3\Tests\Expected\Issue770\Model\IdentityCreateIdentityGuestPass::class;
    }
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \Jane\Component\OpenApi3\Tests\Expected\Issue770\Model\IdentityCreateIdentityGuestPass();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref']) && !isset($data['type']) && !isset($data['properties']) && !isset($data['allOf'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        if (\array_key_exists('autoGeneratedPassword', $data) && \is_int($data['autoGeneratedPassword'])) {
            $data['autoGeneratedPassword'] = (bool) $data['autoGeneratedPassword'];
        }
        if (\array_key_exists('domainId', $data)) {
            $object->domainId = $data['domainId'];
        }
        if (\array_key_exists('guestName', $data)) {
            $object->guestName = $data['guestName'];
        }
        if (\array_key_exists('wlan', $data)) {
            $object->wlan = $this->denormalizer->denormalize($data['wlan'], \Jane\Component\OpenApi3\Tests\Expected\Issue770\Model\CommonGenericRef::class, 'json', $context);
        }
        if (\array_key_exists('zone', $data)) {
            $object->zone = $this->denormalizer->denormalize($data['zone'], \Jane\Component\OpenApi3\Tests\Expected\Issue770\Model\CommonGenericRef::class, 'json', $context);
        }
        if (\array_key_exists('numberOfPasses', $data)) {
            $object->numberOfPasses = $data['numberOfPasses'];
        }
        if (\array_key_exists('passValidFor', $data)) {
            $object->passValidFor = $this->denormalizer->denormalize($data['passValidFor'], \Jane\Component\OpenApi3\Tests\Expected\Issue770\Model\IdentityPassValidFor::class, 'json', $context);
        }
        if (\array_key_exists('autoGeneratedPassword', $data)) {
            $object->autoGeneratedPassword = $data['autoGeneratedPassword'];
        }
        if (\array_key_exists('passValue', $data)) {
            $object->passValue = $data['passValue'];
        }
        if (\array_key_exists('passEffectSince', $data)) {
            $object->passEffectSince = $data['passEffectSince'];
        }
        if (\array_key_exists('passUseDays', $data)) {
            $object->passUseDays = $data['passUseDays'];
        }
        if (\array_key_exists('maxDevices', $data)) {
            $object->maxDevices = $this->denormalizer->denormalize($data['maxDevices'], \Jane\Component\OpenApi3\Tests\Expected\Issue770\Model\IdentityMaxDevices::class, 'json', $context);
        }
        if (\array_key_exists('sessionDuration', $data)) {
            $object->sessionDuration = $this->denormalizer->denormalize($data['sessionDuration'], \Jane\Component\OpenApi3\Tests\Expected\Issue770\Model\IdentitySessionDuration::class, 'json', $context);
        }
        if (\array_key_exists('remarks', $data)) {
            $object->remarks = $data['remarks'];
        }
        return $object;
    }
    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if (array_key_exists('domainId', get_object_vars($data)) && null !== ($data->domainId ?? null)) {
            $dataArray['domainId'] = $data->domainId;
        }
        $dataArray['guestName'] = $data->guestName;
        $normalized = $data->wlan === null ? null : $this->normalizer->normalize($data->wlan, 'json', $context);
        $dataArray['wlan'] = \is_iterable($normalized) ? new \Jane\Component\OpenApi3\Tests\Expected\Issue770\Runtime\JsonObject($normalized) : $normalized;
        $normalized_1 = $data->zone === null ? null : $this->normalizer->normalize($data->zone, 'json', $context);
        $dataArray['zone'] = \is_iterable($normalized_1) ? new \Jane\Component\OpenApi3\Tests\Expected\Issue770\Runtime\JsonObject($normalized_1) : $normalized_1;
        $dataArray['numberOfPasses'] = $data->numberOfPasses;
        $normalized_2 = $data->passValidFor === null ? null : $this->normalizer->normalize($data->passValidFor, 'json', $context);
        $dataArray['passValidFor'] = \is_iterable($normalized_2) ? new \Jane\Component\OpenApi3\Tests\Expected\Issue770\Runtime\JsonObject($normalized_2) : $normalized_2;
        if (array_key_exists('autoGeneratedPassword', get_object_vars($data)) && null !== ($data->autoGeneratedPassword ?? null)) {
            $dataArray['autoGeneratedPassword'] = $data->autoGeneratedPassword;
        }
        if (array_key_exists('passValue', get_object_vars($data)) && null !== ($data->passValue ?? null)) {
            $dataArray['passValue'] = $data->passValue;
        }
        $dataArray['passEffectSince'] = $data->passEffectSince;
        if (array_key_exists('passUseDays', get_object_vars($data)) && null !== ($data->passUseDays ?? null)) {
            $dataArray['passUseDays'] = $data->passUseDays;
        }
        $normalized_3 = $data->maxDevices === null ? null : $this->normalizer->normalize($data->maxDevices, 'json', $context);
        $dataArray['maxDevices'] = \is_iterable($normalized_3) ? new \Jane\Component\OpenApi3\Tests\Expected\Issue770\Runtime\JsonObject($normalized_3) : $normalized_3;
        if (array_key_exists('sessionDuration', get_object_vars($data)) && null !== ($data->sessionDuration ?? null)) {
            $normalized_4 = $this->normalizer->normalize($data->sessionDuration, 'json', $context);
            $dataArray['sessionDuration'] = \is_iterable($normalized_4) ? new \Jane\Component\OpenApi3\Tests\Expected\Issue770\Runtime\JsonObject($normalized_4) : $normalized_4;
        }
        if (array_key_exists('remarks', get_object_vars($data)) && null !== ($data->remarks ?? null)) {
            $dataArray['remarks'] = $data->remarks;
        }
        return $dataArray;
    }
    public function getSupportedTypes(?string $format = null): array
    {
        return [\Jane\Component\OpenApi3\Tests\Expected\Issue770\Model\IdentityCreateIdentityGuestPass::class => false];
    }
}