<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected\Resource;

class FooResource extends \Jane\OpenApiRuntime\Client\Psr7HttplugResource
{
    use FooResourceTrait;
}
