<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi31\JsonSchema\Model;

class ExternalDocumentation
{
    public ?string $description;
    public ?string $url;
}
