<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi31\JsonSchema\Model;

class OpenApi
{
    public ?string $openapi;
    public ?Info $info;
    public ?string $jsonSchemaDialect = 'https://spec.openapis.org/oas/3.1/dialect/base';
    /**
     * @var list<Server>|null
     */
    public ?array $servers = [0 => ['url' => '/']];
    /**
     * @var PathItem[]|null
     */
    public $paths;
    /**
     * @var array<string, mixed>|null
     */
    public ?iterable $webhooks;
    public ?Components $components;
    /**
     * @var list<array<string, list<string>>>|null
     */
    public ?array $security;
    /**
     * @var list<Tag>|null
     */
    public ?array $tags;
    public ?ExternalDocumentation $externalDocs;
}
