<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi31\JsonSchema\Model;

use Jane\Component\OpenApi31\JsonSchema\Runtime\AdditionalAndPatternProperties;
use Jane\Component\OpenApi31\JsonSchema\Runtime\AdditionalPropertiesInterface;

class Operation implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    /**
     * @var list<string>|null
     */
    public ?array $tags;
    public ?string $summary;
    public ?string $description;
    public ?ExternalDocumentation $externalDocs;
    public ?string $operationId;
    /**
     * @var list<mixed>|null
     */
    public ?array $parameters;
    /**
     * @var mixed|null
     */
    public $requestBody;
    public ?Responses $responses;
    /**
     * @var array<string, mixed>|null
     */
    public ?iterable $callbacks;
    public ?bool $deprecated = false;
    /**
     * @var list<array<string, list<string>>>|null
     */
    public ?array $security;
    /**
     * @var list<Server>|null
     */
    public ?array $servers;

    public function definedProperties(): array
    {
        return ['tags' => 'tags', 'summary' => 'summary', 'description' => 'description', 'externalDocs' => 'externalDocs', 'operationId' => 'operationId', 'parameters' => 'parameters', 'requestBody' => 'requestBody', 'responses' => 'responses', 'callbacks' => 'callbacks', 'deprecated' => 'deprecated', 'security' => 'security', 'servers' => 'servers'];
    }
}
