<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi31\JsonSchema\Model;

class ServerVariable
{
    /**
     * @var list<string>|null
     */
    public ?array $enum;
    public ?string $default;
    public ?string $description;
}
