<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi2\JsonSchema\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use Jane\Component\OpenApi2\JsonSchema\Runtime\Normalizer\CheckArray;
use Jane\Component\OpenApi2\JsonSchema\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class BodyParameterNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Jane\Component\OpenApi2\JsonSchema\Model\BodyParameter::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return $data instanceof \Jane\Component\OpenApi2\JsonSchema\Model\BodyParameter;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \Jane\Component\OpenApi2\JsonSchema\Model\BodyParameter();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref']) && !isset($data['type']) && !isset($data['properties']) && !isset($data['allOf'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        if (\array_key_exists('required', $data) && \is_int($data['required'])) {
            $data['required'] = (bool) $data['required'];
        }
        if (\array_key_exists('description', $data) && $data['description'] !== null) {
            $object->description = $data['description'];
            unset($data['description']);
        } elseif (\array_key_exists('description', $data) && $data['description'] === null) {
            $object->description = null;
            unset($data['description']);
        }
        if (\array_key_exists('name', $data) && $data['name'] !== null) {
            $object->name = $data['name'];
            unset($data['name']);
        } elseif (\array_key_exists('name', $data) && $data['name'] === null) {
            $object->name = null;
            unset($data['name']);
        }
        if (\array_key_exists('in', $data) && $data['in'] !== null) {
            $object->in = $data['in'];
            unset($data['in']);
        } elseif (\array_key_exists('in', $data) && $data['in'] === null) {
            $object->in = null;
            unset($data['in']);
        }
        if (\array_key_exists('required', $data) && $data['required'] !== null) {
            $object->required = $data['required'];
            unset($data['required']);
        } elseif (\array_key_exists('required', $data) && $data['required'] === null) {
            $object->required = null;
            unset($data['required']);
        }
        if (\array_key_exists('schema', $data) && $data['schema'] !== null) {
            $value = $data['schema'];
            if (is_array($data['schema'])) {
                $value = $this->denormalizer->denormalize($data['schema'], \Jane\Component\OpenApi2\JsonSchema\Model\Schema::class, 'json', $context);
            } elseif (is_array($data['schema']) and \array_key_exists('$ref', $data['schema'])) {
                $value = $this->denormalizer->denormalize($data['schema'], \Jane\Component\OpenApi2\JsonSchema\Model\JsonReference::class, 'json', $context);
            }
            $object->schema = $value;
            unset($data['schema']);
        } elseif (\array_key_exists('schema', $data) && $data['schema'] === null) {
            $object->schema = null;
            unset($data['schema']);
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/^x-/', (string) $key)) {
                $object[$key] = $value_1;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if (array_key_exists('description', get_object_vars($data)) && null !== ($data->description ?? null)) {
            $dataArray['description'] = $data->description ?? null;
        }
        $dataArray['name'] = $data->name ?? null;
        $dataArray['in'] = $data->in ?? null;
        if (array_key_exists('required', get_object_vars($data)) && null !== ($data->required ?? null)) {
            $dataArray['required'] = $data->required ?? null;
        }
        $value = $data->schema ?? null;
        if (is_object($data->schema ?? null)) {
            $value = ($data->schema ?? null) === null ? null : new \Jane\Component\OpenApi2\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($data->schema ?? null, 'json', $context));
        } elseif (is_object($data->schema ?? null)) {
            $value = ($data->schema ?? null) === null ? null : new \Jane\Component\OpenApi2\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($data->schema ?? null, 'json', $context));
        }
        $dataArray['schema'] = $value;
        foreach ($data->additionalPropertyEntries() as $key => $value_1) {
            if (preg_match('/^x-/', (string) $key)) {
                $dataArray[$key] = $value_1;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Jane\Component\OpenApi2\JsonSchema\Model\BodyParameter::class => false];
    }
}
