<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected\Resource;

use Jane\OpenApiRuntime\Client\QueryParam;

trait TestResourceTrait
{
    /**
     * @param array $testBody
     * @param array $parameters {
     *
     *     @var string $testQuery
     *     @var string $testHeader
     * }
     *
     * @param string $fetch Fetch mode (object or response)
     *
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function testGetWithPathParameters(array $testBody, array $parameters = [], string $fetch = self::FETCH_OBJECT)
    {
        $queryParam = new QueryParam();
        $queryParam->setDefault('testQuery', null);
        $queryParam->setDefault('testHeader', null);
        $queryParam->setHeaderParameters(['testHeader']);
        $url = '/test-path-parameters/{testPath}';
        $url = $url . ('?' . $queryParam->buildQueryString($parameters));
        $headers = array_merge(['Content-Type' => 'application/json'], $queryParam->buildHeaders($parameters));
        $body = $testBody;
        $request = $this->messageFactory->createRequest('GET', $url, $headers, $body);
        $response = $this->httpClient->sendRequest($request);

        return $response;
    }

    /**
     * @param array $testBody
     * @param array $parameters {
     *
     *     @var string $testQuery
     *     @var string $testHeader
     * }
     *
     * @param string $fetch Fetch mode (object or response)
     *
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function testPostWithPathParameters(array $testBody, array $parameters = [], string $fetch = self::FETCH_OBJECT)
    {
        $queryParam = new QueryParam();
        $queryParam->setDefault('testQuery', null);
        $queryParam->setDefault('testHeader', null);
        $queryParam->setHeaderParameters(['testHeader']);
        $url = '/test-path-parameters/{testPath}';
        $url = $url . ('?' . $queryParam->buildQueryString($parameters));
        $headers = array_merge(['Content-Type' => 'application/json'], $queryParam->buildHeaders($parameters));
        $body = $testBody;
        $request = $this->messageFactory->createRequest('POST', $url, $headers, $body);
        $response = $this->httpClient->sendRequest($request);

        return $response;
    }

    /**
     * @param array $parameters {
     *
     *     @var string $testString
     *     @var int $testInteger
     *     @var float $testFloat
     *     @var array $testArray
     *     @var string $testRequired
     *     @var string $testDefault
     * }
     *
     * @param string $fetch Fetch mode (object or response)
     *
     * @return \Psr\Http\Message\ResponseInterface|null
     */
    public function testQueryParameters(array $parameters = [], string $fetch = self::FETCH_OBJECT)
    {
        $queryParam = new QueryParam();
        $queryParam->setDefault('testString', null);
        $queryParam->setDefault('testInteger', null);
        $queryParam->setDefault('testFloat', null);
        $queryParam->setDefault('testArray', null);
        $queryParam->setRequired('testRequired');
        $queryParam->setDefault('testDefault', 'test');
        $url = '/test-query';
        $url = $url . ('?' . $queryParam->buildQueryString($parameters));
        $headers = $queryParam->buildHeaders($parameters);
        $body = $queryParam->buildFormDataString($parameters);
        $request = $this->messageFactory->createRequest('GET', $url, $headers, $body);
        $response = $this->httpClient->sendRequest($request);
        if (self::FETCH_OBJECT === $fetch) {
            if (200 === $response->getStatusCode()) {
                return null;
            }
        }

        return $response;
    }

    /**
     * @param array $parameters {
     *
     *     @var string $testString
     *     @var int $testInteger
     *     @var float $testFloat
     *     @var array $testArray
     *     @var string $testRequired
     *     @var string $testDefault
     * }
     *
     * @param string $fetch Fetch mode (object or response)
     *
     * @return \Psr\Http\Message\ResponseInterface|null
     */
    public function testHeaderParameters(array $parameters = [], string $fetch = self::FETCH_OBJECT)
    {
        $queryParam = new QueryParam();
        $queryParam->setDefault('testString', null);
        $queryParam->setHeaderParameters(['testString']);
        $queryParam->setDefault('testInteger', null);
        $queryParam->setHeaderParameters(['testInteger']);
        $queryParam->setDefault('testFloat', null);
        $queryParam->setHeaderParameters(['testFloat']);
        $queryParam->setDefault('testArray', null);
        $queryParam->setHeaderParameters(['testArray']);
        $queryParam->setRequired('testRequired');
        $queryParam->setHeaderParameters(['testRequired']);
        $queryParam->setDefault('testDefault', 'test');
        $queryParam->setHeaderParameters(['testDefault']);
        $url = '/test-header';
        $url = $url . ('?' . $queryParam->buildQueryString($parameters));
        $headers = $queryParam->buildHeaders($parameters);
        $body = $queryParam->buildFormDataString($parameters);
        $request = $this->messageFactory->createRequest('GET', $url, $headers, $body);
        $response = $this->httpClient->sendRequest($request);
        if (self::FETCH_OBJECT === $fetch) {
            if (200 === $response->getStatusCode()) {
                return null;
            }
        }

        return $response;
    }

    /**
     * @param array $parameters {
     *
     *     @var string $testString
     *     @var int $testInteger
     *     @var float $testFloat
     *     @var array $testArray
     *     @var string $testRequired
     *     @var string $testDefault
     * }
     *
     * @param string $fetch Fetch mode (object or response)
     *
     * @return \Psr\Http\Message\ResponseInterface|null
     */
    public function testFormParameters(array $parameters = [], string $fetch = self::FETCH_OBJECT)
    {
        $queryParam = new QueryParam();
        $queryParam->setDefault('testString', null);
        $queryParam->setFormParameters(['testString']);
        $queryParam->setDefault('testInteger', null);
        $queryParam->setFormParameters(['testInteger']);
        $queryParam->setDefault('testFloat', null);
        $queryParam->setFormParameters(['testFloat']);
        $queryParam->setDefault('testArray', null);
        $queryParam->setFormParameters(['testArray']);
        $queryParam->setRequired('testRequired');
        $queryParam->setFormParameters(['testRequired']);
        $queryParam->setDefault('testDefault', 'test');
        $queryParam->setFormParameters(['testDefault']);
        $url = '/test-form';
        $url = $url . ('?' . $queryParam->buildQueryString($parameters));
        $headers = array_merge(['Content-Type' => 'application/x-www-form-urlencoded'], $queryParam->buildHeaders($parameters));
        $body = $queryParam->buildFormDataString($parameters);
        $request = $this->messageFactory->createRequest('POST', $url, $headers, $body);
        $response = $this->httpClient->sendRequest($request);
        if (self::FETCH_OBJECT === $fetch) {
            if (200 === $response->getStatusCode()) {
                return null;
            }
        }

        return $response;
    }

    /**
     * @param string $testString
     * @param int    $testInteger
     * @param float  $testFloat
     * @param array  $parameters  List of parameters
     * @param string $fetch       Fetch mode (object or response)
     *
     * @return \Psr\Http\Message\ResponseInterface|null
     */
    public function testPathParameters(string $testString, int $testInteger, float $testFloat, array $parameters = [], string $fetch = self::FETCH_OBJECT)
    {
        $queryParam = new QueryParam();
        $url = '/test-path/{testString}/{testInteger}/{testFloat}';
        $url = str_replace('{testString}', urlencode($testString), $url);
        $url = str_replace('{testInteger}', urlencode($testInteger), $url);
        $url = str_replace('{testFloat}', urlencode($testFloat), $url);
        $url = $url . ('?' . $queryParam->buildQueryString($parameters));
        $headers = $queryParam->buildHeaders($parameters);
        $body = $queryParam->buildFormDataString($parameters);
        $request = $this->messageFactory->createRequest('GET', $url, $headers, $body);
        $response = $this->httpClient->sendRequest($request);
        if (self::FETCH_OBJECT === $fetch) {
            if (200 === $response->getStatusCode()) {
                return null;
            }
        }

        return $response;
    }

    /**
     * @param int    $testInteger
     * @param array  $parameters  List of parameters
     * @param string $fetch       Fetch mode (object or response)
     *
     * @return \Psr\Http\Message\ResponseInterface|null
     */
    public function getByTestInteger(int $testInteger, array $parameters = [], string $fetch = self::FETCH_OBJECT)
    {
        $queryParam = new QueryParam();
        $url = '/{test_integer}';
        $url = str_replace('{test_integer}', urlencode($testInteger), $url);
        $url = $url . ('?' . $queryParam->buildQueryString($parameters));
        $headers = $queryParam->buildHeaders($parameters);
        $body = $queryParam->buildFormDataString($parameters);
        $request = $this->messageFactory->createRequest('GET', $url, $headers, $body);
        $response = $this->httpClient->sendRequest($request);
        if (self::FETCH_OBJECT === $fetch) {
            if (200 === $response->getStatusCode()) {
                return null;
            }
        }

        return $response;
    }
}
