<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected\Resource;

use Jane\OpenApiRuntime\Client\QueryParam;

trait DefaultResourceTrait
{
    /**
     * @param array  $parameters List of parameters
     * @param string $fetch      Fetch mode (object or response)
     *
     * @throws \Jane\OpenApi\Tests\Expected\Exception\TestNoTagBadRequestException
     * @throws \Jane\OpenApi\Tests\Expected\Exception\TestNoTagNotFoundException
     * @throws \Jane\OpenApi\Tests\Expected\Exception\TestNoTagInternalServerErrorException
     *
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function testNoTag(array $parameters = [], string $fetch = self::FETCH_OBJECT)
    {
        $queryParam = new QueryParam($this->streamFactory);
        $url = '/test-exception';
        $url = $url . ('?' . $queryParam->buildQueryString($parameters));
        $headers = $queryParam->buildHeaders($parameters);
        $body = $queryParam->buildFormDataString($parameters);
        $request = $this->messageFactory->createRequest('GET', $url, $headers, $body);
        $response = $this->httpClient->sendRequest($request);
        if (self::FETCH_OBJECT === $fetch) {
            if (400 === $response->getStatusCode()) {
                throw new \Jane\OpenApi\Tests\Expected\Exception\TestNoTagBadRequestException($this->serializer->deserialize((string) $response->getBody(), 'Jane\\OpenApi\\Tests\\Expected\\Model\\Error', 'json'));
            }
            if (404 === $response->getStatusCode()) {
                throw new \Jane\OpenApi\Tests\Expected\Exception\TestNoTagNotFoundException();
            }
            if (500 === $response->getStatusCode()) {
                throw new \Jane\OpenApi\Tests\Expected\Exception\TestNoTagInternalServerErrorException();
            }
        }

        return $response;
    }
}
