<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\JsonSchema\Version3\Normalizer;

class NormalizerFactory
{
    public static function create()
    {
        $normalizers = [];
        $normalizers[] = new \Symfony\Component\Serializer\Normalizer\ArrayDenormalizer();
        $normalizers[] = new \Jane\JsonSchemaRuntime\Normalizer\ReferenceNormalizer();
        $normalizers[] = new OpenApiNormalizer();
        $normalizers[] = new ReferenceNormalizer();
        $normalizers[] = new InfoNormalizer();
        $normalizers[] = new ContactNormalizer();
        $normalizers[] = new LicenseNormalizer();
        $normalizers[] = new ServerNormalizer();
        $normalizers[] = new ServerVariableNormalizer();
        $normalizers[] = new ComponentsNormalizer();
        $normalizers[] = new SchemaNormalizer();
        $normalizers[] = new DiscriminatorNormalizer();
        $normalizers[] = new XMLNormalizer();
        $normalizers[] = new ResponseNormalizer();
        $normalizers[] = new MediaTypeWithExampleNormalizer();
        $normalizers[] = new MediaTypeWithExamplesNormalizer();
        $normalizers[] = new ExampleNormalizer();
        $normalizers[] = new HeaderWithSchemaWithExampleNormalizer();
        $normalizers[] = new HeaderWithSchemaWithExamplesNormalizer();
        $normalizers[] = new HeaderWithContentNormalizer();
        $normalizers[] = new PathItemNormalizer();
        $normalizers[] = new OperationNormalizer();
        $normalizers[] = new ResponsesNormalizer();
        $normalizers[] = new TagNormalizer();
        $normalizers[] = new ExternalDocumentationNormalizer();
        $normalizers[] = new ParameterWithSchemaWithExampleInPathNormalizer();
        $normalizers[] = new ParameterWithSchemaWithExampleInQueryNormalizer();
        $normalizers[] = new ParameterWithSchemaWithExampleInHeaderNormalizer();
        $normalizers[] = new ParameterWithSchemaWithExampleInCookieNormalizer();
        $normalizers[] = new ParameterWithSchemaWithExamplesInPathNormalizer();
        $normalizers[] = new ParameterWithSchemaWithExamplesInQueryNormalizer();
        $normalizers[] = new ParameterWithSchemaWithExamplesInHeaderNormalizer();
        $normalizers[] = new ParameterWithSchemaWithExamplesInCookieNormalizer();
        $normalizers[] = new ParameterWithContentInPathNormalizer();
        $normalizers[] = new ParameterWithContentNotInPathNormalizer();
        $normalizers[] = new RequestBodyNormalizer();
        $normalizers[] = new APIKeySecuritySchemeNormalizer();
        $normalizers[] = new NonBearerHTTPSecuritySchemeNormalizer();
        $normalizers[] = new BearerHTTPSecuritySchemeNormalizer();
        $normalizers[] = new OAuth2SecuritySchemeNormalizer();
        $normalizers[] = new OpenIdConnectSecuritySchemeNormalizer();
        $normalizers[] = new OAuthFlowsNormalizer();
        $normalizers[] = new ImplicitOAuthFlowNormalizer();
        $normalizers[] = new PasswordOAuthFlowNormalizer();
        $normalizers[] = new ClientCredentialsFlowNormalizer();
        $normalizers[] = new AuthorizationCodeOAuthFlowNormalizer();
        $normalizers[] = new LinkWithOperationRefNormalizer();
        $normalizers[] = new LinkWithOperationIdNormalizer();
        $normalizers[] = new EncodingNormalizer();

        return $normalizers;
    }
}
