<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected\Api2\Resource;

trait TestResourceTrait
{
    /**
     * @param string $fetch Fetch mode to use (can be OBJECT or RESPONSE)
     *
     * @return null|\Jane\OpenApi\Tests\Expected\Api1\Model\Body|\Psr\Http\Message\ResponseInterface
     */
    public function testReferenceResponse(string $fetch = self::FETCH_OBJECT)
    {
        $endpoint = new \Jane\OpenApi\Tests\Expected\Api2\Endpoint\TestReferenceResponse();

        return $this->executePsr7Endpoint($endpoint, $fetch);
    }
}
