<?php

namespace Jane\Component\OpenApi3\Tests\Expected\Model;

class IdentityCreateIdentityGuestPass
{
    /**
     * @var array
     */
    protected $initialized = [];
    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Domain Id
     *
     * @var string
     */
    protected $domainId;
    /**
     * @var string
     */
    protected $guestName;
    /**
     * @var CommonGenericRef
     */
    protected $wlan;
    /**
     * @var CommonGenericRef
     */
    protected $zone;
    /**
     * Number of passes
     *
     * @var int
     */
    protected $numberOfPasses;
    /**
     * @var IdentityPassValidFor
     */
    protected $passValidFor;
    /**
     * Pass generation
     *
     * @var bool
     */
    protected $autoGeneratedPassword;
    /**
     * Pass value
     *
     * @var string
     */
    protected $passValue;
    /**
     * Pass effective since
     *
     * @var string
     */
    protected $passEffectSince;
    /**
     * Expire new guest pass if not used within
     *
     * @var int
     */
    protected $passUseDays;
    /**
     * @var IdentityMaxDevices
     */
    protected $maxDevices;
    /**
     * @var IdentitySessionDuration
     */
    protected $sessionDuration;
    /**
     * Remarks
     *
     * @var string
     */
    protected $remarks;
    /**
     * Domain Id
     *
     * @return string
     */
    public function getDomainId(): string
    {
        return $this->domainId;
    }
    /**
     * Domain Id
     *
     * @param string $domainId
     *
     * @return self
     */
    public function setDomainId(string $domainId): self
    {
        $this->initialized['domainId'] = true;
        $this->domainId = $domainId;
        return $this;
    }
    /**
     * @return string
     */
    public function getGuestName(): string
    {
        return $this->guestName;
    }
    /**
     * @param string $guestName
     *
     * @return self
     */
    public function setGuestName(string $guestName): self
    {
        $this->initialized['guestName'] = true;
        $this->guestName = $guestName;
        return $this;
    }
    /**
     * @return CommonGenericRef
     */
    public function getWlan(): CommonGenericRef
    {
        return $this->wlan;
    }
    /**
     * @param CommonGenericRef $wlan
     *
     * @return self
     */
    public function setWlan(CommonGenericRef $wlan): self
    {
        $this->initialized['wlan'] = true;
        $this->wlan = $wlan;
        return $this;
    }
    /**
     * @return CommonGenericRef
     */
    public function getZone(): CommonGenericRef
    {
        return $this->zone;
    }
    /**
     * @param CommonGenericRef $zone
     *
     * @return self
     */
    public function setZone(CommonGenericRef $zone): self
    {
        $this->initialized['zone'] = true;
        $this->zone = $zone;
        return $this;
    }
    /**
     * Number of passes
     *
     * @return int
     */
    public function getNumberOfPasses(): int
    {
        return $this->numberOfPasses;
    }
    /**
     * Number of passes
     *
     * @param int $numberOfPasses
     *
     * @return self
     */
    public function setNumberOfPasses(int $numberOfPasses): self
    {
        $this->initialized['numberOfPasses'] = true;
        $this->numberOfPasses = $numberOfPasses;
        return $this;
    }
    /**
     * @return IdentityPassValidFor
     */
    public function getPassValidFor(): IdentityPassValidFor
    {
        return $this->passValidFor;
    }
    /**
     * @param IdentityPassValidFor $passValidFor
     *
     * @return self
     */
    public function setPassValidFor(IdentityPassValidFor $passValidFor): self
    {
        $this->initialized['passValidFor'] = true;
        $this->passValidFor = $passValidFor;
        return $this;
    }
    /**
     * Pass generation
     *
     * @return bool
     */
    public function getAutoGeneratedPassword(): bool
    {
        return $this->autoGeneratedPassword;
    }
    /**
     * Pass generation
     *
     * @param bool $autoGeneratedPassword
     *
     * @return self
     */
    public function setAutoGeneratedPassword(bool $autoGeneratedPassword): self
    {
        $this->initialized['autoGeneratedPassword'] = true;
        $this->autoGeneratedPassword = $autoGeneratedPassword;
        return $this;
    }
    /**
     * Pass value
     *
     * @return string
     */
    public function getPassValue(): string
    {
        return $this->passValue;
    }
    /**
     * Pass value
     *
     * @param string $passValue
     *
     * @return self
     */
    public function setPassValue(string $passValue): self
    {
        $this->initialized['passValue'] = true;
        $this->passValue = $passValue;
        return $this;
    }
    /**
     * Pass effective since
     *
     * @return string
     */
    public function getPassEffectSince(): string
    {
        return $this->passEffectSince;
    }
    /**
     * Pass effective since
     *
     * @param string $passEffectSince
     *
     * @return self
     */
    public function setPassEffectSince(string $passEffectSince): self
    {
        $this->initialized['passEffectSince'] = true;
        $this->passEffectSince = $passEffectSince;
        return $this;
    }
    /**
     * Expire new guest pass if not used within
     *
     * @return int
     */
    public function getPassUseDays(): int
    {
        return $this->passUseDays;
    }
    /**
     * Expire new guest pass if not used within
     *
     * @param int $passUseDays
     *
     * @return self
     */
    public function setPassUseDays(int $passUseDays): self
    {
        $this->initialized['passUseDays'] = true;
        $this->passUseDays = $passUseDays;
        return $this;
    }
    /**
     * @return IdentityMaxDevices
     */
    public function getMaxDevices(): IdentityMaxDevices
    {
        return $this->maxDevices;
    }
    /**
     * @param IdentityMaxDevices $maxDevices
     *
     * @return self
     */
    public function setMaxDevices(IdentityMaxDevices $maxDevices): self
    {
        $this->initialized['maxDevices'] = true;
        $this->maxDevices = $maxDevices;
        return $this;
    }
    /**
     * @return IdentitySessionDuration
     */
    public function getSessionDuration(): IdentitySessionDuration
    {
        return $this->sessionDuration;
    }
    /**
     * @param IdentitySessionDuration $sessionDuration
     *
     * @return self
     */
    public function setSessionDuration(IdentitySessionDuration $sessionDuration): self
    {
        $this->initialized['sessionDuration'] = true;
        $this->sessionDuration = $sessionDuration;
        return $this;
    }
    /**
     * Remarks
     *
     * @return string
     */
    public function getRemarks(): string
    {
        return $this->remarks;
    }
    /**
     * Remarks
     *
     * @param string $remarks
     *
     * @return self
     */
    public function setRemarks(string $remarks): self
    {
        $this->initialized['remarks'] = true;
        $this->remarks = $remarks;
        return $this;
    }
}