<?php

namespace Jane\Component\OpenApi3\Tests\Expected\Model;

class IdentityCreateIdentityGuestPass
{
    /**
     * Domain Id
     *
     * @var string
     */
    public string $domainId;
    /**
     * @var string
     */
    public string $guestName;
    /**
     * @var CommonGenericRef
     */
    public CommonGenericRef $wlan;
    /**
     * @var CommonGenericRef
     */
    public CommonGenericRef $zone;
    /**
     * Number of passes
     *
     * @var int
     */
    public int $numberOfPasses;
    /**
     * @var IdentityPassValidFor
     */
    public IdentityPassValidFor $passValidFor;
    /**
     * Pass generation
     *
     * @var bool
     */
    public bool $autoGeneratedPassword;
    /**
     * Pass value
     *
     * @var string
     */
    public string $passValue;
    /**
     * Pass effective since
     *
     * @var string
     */
    public string $passEffectSince;
    /**
     * Expire new guest pass if not used within
     *
     * @var int
     */
    public int $passUseDays;
    /**
     * @var IdentityMaxDevices
     */
    public IdentityMaxDevices $maxDevices;
    /**
     * @var IdentitySessionDuration
     */
    public IdentitySessionDuration $sessionDuration;
    /**
     * Remarks
     *
     * @var string
     */
    public string $remarks;
}