<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\JsonSchema\Version3\Model;

class Discriminator
{
    /**
     * @var string
     */
    protected $propertyName;
    /**
     * @var string[]
     */
    protected $mapping;

    /**
     * @return string
     */
    public function getPropertyName(): ?string
    {
        return $this->propertyName;
    }

    /**
     * @param string $propertyName
     *
     * @return self
     */
    public function setPropertyName(?string $propertyName): self
    {
        $this->propertyName = $propertyName;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getMapping(): ?\ArrayObject
    {
        return $this->mapping;
    }

    /**
     * @param string[] $mapping
     *
     * @return self
     */
    public function setMapping(?\ArrayObject $mapping): self
    {
        $this->mapping = $mapping;

        return $this;
    }
}
