<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\JsonSchema\Version3\Model;

class LinkWithOperationRef extends \ArrayObject
{
    /**
     * @var string
     */
    protected $operationRef;
    /**
     * @var mixed[]
     */
    protected $parameters;
    /**
     * @var mixed
     */
    protected $requestBody;
    /**
     * @var string
     */
    protected $description;
    /**
     * @var Server
     */
    protected $server;

    /**
     * @return string
     */
    public function getOperationRef(): ?string
    {
        return $this->operationRef;
    }

    /**
     * @param string $operationRef
     *
     * @return self
     */
    public function setOperationRef(?string $operationRef): self
    {
        $this->operationRef = $operationRef;

        return $this;
    }

    /**
     * @return mixed[]
     */
    public function getParameters(): ?\ArrayObject
    {
        return $this->parameters;
    }

    /**
     * @param mixed[] $parameters
     *
     * @return self
     */
    public function setParameters(?\ArrayObject $parameters): self
    {
        $this->parameters = $parameters;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRequestBody()
    {
        return $this->requestBody;
    }

    /**
     * @param mixed $requestBody
     *
     * @return self
     */
    public function setRequestBody($requestBody): self
    {
        $this->requestBody = $requestBody;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     *
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Server
     */
    public function getServer(): ?Server
    {
        return $this->server;
    }

    /**
     * @param Server $server
     *
     * @return self
     */
    public function setServer(?Server $server): self
    {
        $this->server = $server;

        return $this;
    }
}
