<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\JsonSchema\Version3\Model;

class OAuthFlows extends \ArrayObject
{
    /**
     * @var ImplicitOAuthFlow
     */
    protected $implicit;
    /**
     * @var PasswordOAuthFlow
     */
    protected $password;
    /**
     * @var ClientCredentialsFlow
     */
    protected $clientCredentials;
    /**
     * @var AuthorizationCodeOAuthFlow
     */
    protected $authorizationCode;

    /**
     * @return ImplicitOAuthFlow
     */
    public function getImplicit(): ?ImplicitOAuthFlow
    {
        return $this->implicit;
    }

    /**
     * @param ImplicitOAuthFlow $implicit
     *
     * @return self
     */
    public function setImplicit(?ImplicitOAuthFlow $implicit): self
    {
        $this->implicit = $implicit;

        return $this;
    }

    /**
     * @return PasswordOAuthFlow
     */
    public function getPassword(): ?PasswordOAuthFlow
    {
        return $this->password;
    }

    /**
     * @param PasswordOAuthFlow $password
     *
     * @return self
     */
    public function setPassword(?PasswordOAuthFlow $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return ClientCredentialsFlow
     */
    public function getClientCredentials(): ?ClientCredentialsFlow
    {
        return $this->clientCredentials;
    }

    /**
     * @param ClientCredentialsFlow $clientCredentials
     *
     * @return self
     */
    public function setClientCredentials(?ClientCredentialsFlow $clientCredentials): self
    {
        $this->clientCredentials = $clientCredentials;

        return $this;
    }

    /**
     * @return AuthorizationCodeOAuthFlow
     */
    public function getAuthorizationCode(): ?AuthorizationCodeOAuthFlow
    {
        return $this->authorizationCode;
    }

    /**
     * @param AuthorizationCodeOAuthFlow $authorizationCode
     *
     * @return self
     */
    public function setAuthorizationCode(?AuthorizationCodeOAuthFlow $authorizationCode): self
    {
        $this->authorizationCode = $authorizationCode;

        return $this;
    }
}
