<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\JsonSchema\Version3\Model;

class Operation extends \ArrayObject
{
    /**
     * @var string[]
     */
    protected $tags;
    /**
     * @var string
     */
    protected $summary;
    /**
     * @var string
     */
    protected $description;
    /**
     * @var ExternalDocumentation
     */
    protected $externalDocs;
    /**
     * @var string
     */
    protected $operationId;
    /**
     * @var ParameterWithSchemaWithExampleInPath[]|ParameterWithSchemaWithExampleInQuery[]|ParameterWithSchemaWithExampleInHeader[]|ParameterWithSchemaWithExampleInCookie[]|ParameterWithSchemaWithExamplesInPath[]|ParameterWithSchemaWithExamplesInQuery[]|ParameterWithSchemaWithExamplesInHeader[]|ParameterWithSchemaWithExamplesInCookie[]|ParameterWithContentInPath[]|ParameterWithContentNotInPath[]|Reference[]
     */
    protected $parameters;
    /**
     * @var RequestBody|Reference
     */
    protected $requestBody;
    /**
     * @var Responses
     */
    protected $responses;
    /**
     * @var mixed[][]|Reference[]
     */
    protected $callbacks;
    /**
     * @var bool
     */
    protected $deprecated;
    /**
     * @var string[][][]
     */
    protected $security;
    /**
     * @var Server[]
     */
    protected $servers;

    /**
     * @return string[]
     */
    public function getTags(): ?array
    {
        return $this->tags;
    }

    /**
     * @param string[] $tags
     *
     * @return self
     */
    public function setTags(?array $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * @return string
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * @param string $summary
     *
     * @return self
     */
    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     *
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return ExternalDocumentation
     */
    public function getExternalDocs(): ?ExternalDocumentation
    {
        return $this->externalDocs;
    }

    /**
     * @param ExternalDocumentation $externalDocs
     *
     * @return self
     */
    public function setExternalDocs(?ExternalDocumentation $externalDocs): self
    {
        $this->externalDocs = $externalDocs;

        return $this;
    }

    /**
     * @return string
     */
    public function getOperationId(): ?string
    {
        return $this->operationId;
    }

    /**
     * @param string $operationId
     *
     * @return self
     */
    public function setOperationId(?string $operationId): self
    {
        $this->operationId = $operationId;

        return $this;
    }

    /**
     * @return ParameterWithSchemaWithExampleInPath[]|ParameterWithSchemaWithExampleInQuery[]|ParameterWithSchemaWithExampleInHeader[]|ParameterWithSchemaWithExampleInCookie[]|ParameterWithSchemaWithExamplesInPath[]|ParameterWithSchemaWithExamplesInQuery[]|ParameterWithSchemaWithExamplesInHeader[]|ParameterWithSchemaWithExamplesInCookie[]|ParameterWithContentInPath[]|ParameterWithContentNotInPath[]|Reference[]
     */
    public function getParameters(): ?array
    {
        return $this->parameters;
    }

    /**
     * @param ParameterWithSchemaWithExampleInPath[]|ParameterWithSchemaWithExampleInQuery[]|ParameterWithSchemaWithExampleInHeader[]|ParameterWithSchemaWithExampleInCookie[]|ParameterWithSchemaWithExamplesInPath[]|ParameterWithSchemaWithExamplesInQuery[]|ParameterWithSchemaWithExamplesInHeader[]|ParameterWithSchemaWithExamplesInCookie[]|ParameterWithContentInPath[]|ParameterWithContentNotInPath[]|Reference[] $parameters
     *
     * @return self
     */
    public function setParameters(?array $parameters): self
    {
        $this->parameters = $parameters;

        return $this;
    }

    /**
     * @return RequestBody|Reference
     */
    public function getRequestBody()
    {
        return $this->requestBody;
    }

    /**
     * @param RequestBody|Reference $requestBody
     *
     * @return self
     */
    public function setRequestBody($requestBody): self
    {
        $this->requestBody = $requestBody;

        return $this;
    }

    /**
     * @return Responses
     */
    public function getResponses(): ?Responses
    {
        return $this->responses;
    }

    /**
     * @param Responses $responses
     *
     * @return self
     */
    public function setResponses(?Responses $responses): self
    {
        $this->responses = $responses;

        return $this;
    }

    /**
     * @return mixed[][]|Reference[]
     */
    public function getCallbacks(): ?\ArrayObject
    {
        return $this->callbacks;
    }

    /**
     * @param mixed[][]|Reference[] $callbacks
     *
     * @return self
     */
    public function setCallbacks(?\ArrayObject $callbacks): self
    {
        $this->callbacks = $callbacks;

        return $this;
    }

    /**
     * @return bool
     */
    public function getDeprecated(): ?bool
    {
        return $this->deprecated;
    }

    /**
     * @param bool $deprecated
     *
     * @return self
     */
    public function setDeprecated(?bool $deprecated): self
    {
        $this->deprecated = $deprecated;

        return $this;
    }

    /**
     * @return string[][][]
     */
    public function getSecurity(): ?array
    {
        return $this->security;
    }

    /**
     * @param string[][][] $security
     *
     * @return self
     */
    public function setSecurity(?array $security): self
    {
        $this->security = $security;

        return $this;
    }

    /**
     * @return Server[]
     */
    public function getServers(): ?array
    {
        return $this->servers;
    }

    /**
     * @param Server[] $servers
     *
     * @return self
     */
    public function setServers(?array $servers): self
    {
        $this->servers = $servers;

        return $this;
    }
}
