<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\JsonSchema\Version3\Model;

class Response extends \ArrayObject
{
    /**
     * @var string
     */
    protected $description;
    /**
     * @var mixed
     */
    protected $headers;
    /**
     * @var MediaTypeWithExample[]|MediaTypeWithExamples[]
     */
    protected $content;
    /**
     * @var LinkWithOperationRef[]|LinkWithOperationId[]|Reference[]
     */
    protected $links;

    /**
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     *
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * @param mixed $headers
     *
     * @return self
     */
    public function setHeaders($headers): self
    {
        $this->headers = $headers;

        return $this;
    }

    /**
     * @return MediaTypeWithExample[]|MediaTypeWithExamples[]
     */
    public function getContent(): ?\ArrayObject
    {
        return $this->content;
    }

    /**
     * @param MediaTypeWithExample[]|MediaTypeWithExamples[] $content
     *
     * @return self
     */
    public function setContent(?\ArrayObject $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return LinkWithOperationRef[]|LinkWithOperationId[]|Reference[]
     */
    public function getLinks(): ?\ArrayObject
    {
        return $this->links;
    }

    /**
     * @param LinkWithOperationRef[]|LinkWithOperationId[]|Reference[] $links
     *
     * @return self
     */
    public function setLinks(?\ArrayObject $links): self
    {
        $this->links = $links;

        return $this;
    }
}
