<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\JsonSchema\Tests\Expected\Model;

class Test
{
    /**
     * @var TestFoo
     */
    protected $foo;

    /**
     * @return TestFoo
     */
    public function getFoo(): ?TestFoo
    {
        return $this->foo;
    }

    /**
     * @param TestFoo $foo
     *
     * @return self
     */
    public function setFoo(?TestFoo $foo): self
    {
        $this->foo = $foo;

        return $this;
    }
}
