<?php

namespace Jane\Component\JsonSchema;

use Jane\Component\JsonSchema\Registry\Registry;
use PhpCsFixer\Console\Command\FixCommand;
use PhpCsFixer\ToolInfo;
use PhpParser\PrettyPrinterAbstract;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;
use Symfony\Component\Console\Output\NullOutput;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

class Printer
{
    private bool $useFixer = false;
    private bool $cleanGenerated = true;
    private ?OutputInterface $output = null;

    /** @var callable(): (Command|null) */
    private $fixerFactory;

    public function __construct(
        private readonly PrettyPrinterAbstract $prettyPrinter,
        private readonly string $fixerConfig = '',
        ?callable $fixerFactory = null,
    ) {
        $this->fixerFactory = $fixerFactory ?? static function (): ?Command {
            if (!class_exists(FixCommand::class)) {
                return null;
            }

            return new FixCommand(new ToolInfo());
        };
    }

    public function setUseFixer(bool $useFixer): void
    {
        $this->useFixer = $useFixer;
    }

    public function setCleanGenerated(bool $cleanGenerated): void
    {
        $this->cleanGenerated = $cleanGenerated;
    }

    public function output(Registry $registry, ?OutputInterface $output = null): void
    {
        $this->output = $output;

        if ($this->cleanGenerated) {
            $fs = new Filesystem();
            foreach ($registry->getOutputDirectories() as $directory) {
                $fs->remove($directory);
                $fs->mkdir($directory);
            }
        }

        foreach ($registry->getSchemas() as $schema) {
            foreach ($schema->getFiles() as $file) {
                if (!file_exists(\dirname($file->getFilename()))) {
                    mkdir(\dirname($file->getFilename()), 0755, true);
                }

                file_put_contents($file->getFilename(), $this->prettyPrinter->prettyPrintFile([$file->getNode()]));
            }
        }

        if ($this->useFixer) {
            foreach ($registry->getOutputDirectories() as $directory) {
                $this->fix($directory);
            }
        }
    }

    protected function getDefaultRules(): string
    {
        $rules = [
            '@Symfony' => true,
            'self_accessor' => true,
            'array_syntax' => ['syntax' => 'short'],
            'concat_space' => ['spacing' => 'one'],
            'declare_strict_types' => true,
            'header_comment' => [
                'header' => <<<EOH
This file has been auto generated by Jane,

Do no edit it directly.
EOH
                ,
            ],
        ];

        if (version_compare(\PhpCsFixer\Console\Application::VERSION, '3.0.0', '>=')) {
            $rules['yoda_style'] = false;
        } elseif (version_compare(\PhpCsFixer\Console\Application::VERSION, '2.6.0', '>=')) {
            $rules['yoda_style'] = null;
        }

        return json_encode($rules);
    }

    protected function fix(string $path): void
    {
        $fixer = ($this->fixerFactory)();

        if (null === $fixer) {
            return;
        }

        $config = [
            'path' => [$path],
        ];

        if (!empty($this->fixerConfig)) {
            $config['--config'] = $this->fixerConfig;
        } else {
            $config['--allow-risky'] = 'yes';
            $config['--rules'] = $this->getDefaultRules();
        }

        $fixerOutput = new BufferedOutput();
        $returnCode = $fixer->run(new ArrayInput($config, $fixer->getDefinition()), $fixerOutput);

        if (Command::SUCCESS !== $returnCode) {
            // Surface the fixer output so the failure cause is visible, then fail loudly.
            $output = $this->output ?? new NullOutput();
            $output->write($fixerOutput->fetch());

            $message = \sprintf('php-cs-fixer failed for directory "%s" with exit code "%s".', $path, $returnCode);
            (new SymfonyStyle(new ArrayInput([]), $output))->warning($message);

            throw new \RuntimeException($message);
        }

        if (null !== $this->output && $this->output->isVerbose()) {
            $this->output->write($fixerOutput->fetch());
        }
    }
}
