<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\CheckArray;
use Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ImplicitOAuthFlowNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Jane\Component\OpenApi3\JsonSchema\Model\ImplicitOAuthFlow::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return $data instanceof \Jane\Component\OpenApi3\JsonSchema\Model\ImplicitOAuthFlow;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \Jane\Component\OpenApi3\JsonSchema\Model\ImplicitOAuthFlow();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref']) && !isset($data['type']) && !isset($data['properties']) && !isset($data['allOf'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        if (\array_key_exists('authorizationUrl', $data) && $data['authorizationUrl'] !== null) {
            $object->authorizationUrl = $data['authorizationUrl'];
            unset($data['authorizationUrl']);
        } elseif (\array_key_exists('authorizationUrl', $data) && $data['authorizationUrl'] === null) {
            $object->authorizationUrl = null;
            unset($data['authorizationUrl']);
        }
        if (\array_key_exists('refreshUrl', $data) && $data['refreshUrl'] !== null) {
            $object->refreshUrl = $data['refreshUrl'];
            unset($data['refreshUrl']);
        } elseif (\array_key_exists('refreshUrl', $data) && $data['refreshUrl'] === null) {
            $object->refreshUrl = null;
            unset($data['refreshUrl']);
        }
        if (\array_key_exists('scopes', $data) && $data['scopes'] !== null) {
            $values = new \Jane\Component\OpenApi3\JsonSchema\Runtime\JsonObject();
            foreach ($data['scopes'] as $key => $value) {
                $values[$key] = $value;
            }
            $object->scopes = $values;
            unset($data['scopes']);
        } elseif (\array_key_exists('scopes', $data) && $data['scopes'] === null) {
            $object->scopes = null;
            unset($data['scopes']);
        }
        foreach ($data as $key_1 => $value_1) {
            if (preg_match('/^x-/', (string) $key_1)) {
                $object[$key_1] = $value_1;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        $dataArray['authorizationUrl'] = $data->authorizationUrl ?? null;
        if (array_key_exists('refreshUrl', get_object_vars($data)) && null !== ($data->refreshUrl ?? null)) {
            $dataArray['refreshUrl'] = $data->refreshUrl ?? null;
        }
        $values = new \Jane\Component\OpenApi3\JsonSchema\Runtime\JsonObject();
        foreach ($data->scopes ?? null as $key => $value) {
            $values[$key] = $value;
        }
        $dataArray['scopes'] = $values;
        foreach ($data->additionalPropertyEntries() as $key_1 => $value_1) {
            if (preg_match('/^x-/', (string) $key_1)) {
                $dataArray[$key_1] = $value_1;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Jane\Component\OpenApi3\JsonSchema\Model\ImplicitOAuthFlow::class => false];
    }
}
