<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Normalizer;

use Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\CheckArray;
use Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class JaneObjectNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;
    protected $normalizers = [
        \Jane\Component\OpenApi3\JsonSchema\Model\OpenApi::class => OpenApiNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Reference::class => ReferenceNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Info::class => InfoNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Contact::class => ContactNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\License::class => LicenseNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Server::class => ServerNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\ServerVariable::class => ServerVariableNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Components::class => ComponentsNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Schema::class => SchemaNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Discriminator::class => DiscriminatorNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\XML::class => XMLNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Response::class => ResponseNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\MediaType::class => MediaTypeNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Example::class => ExampleNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Header::class => HeaderNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\PathItem::class => PathItemNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Operation::class => OperationNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Responses::class => ResponsesNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Tag::class => TagNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\ExternalDocumentation::class => ExternalDocumentationNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Parameter::class => ParameterNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\RequestBody::class => RequestBodyNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\APIKeySecurityScheme::class => APIKeySecuritySchemeNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\HTTPSecurityScheme::class => HTTPSecuritySchemeNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\HTTPSecuritySchemeSub::class => HTTPSecuritySchemeSubNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\OAuth2SecurityScheme::class => OAuth2SecuritySchemeNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\OpenIdConnectSecurityScheme::class => OpenIdConnectSecuritySchemeNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\OAuthFlows::class => OAuthFlowsNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\ImplicitOAuthFlow::class => ImplicitOAuthFlowNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\PasswordOAuthFlow::class => PasswordOAuthFlowNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\ClientCredentialsFlow::class => ClientCredentialsFlowNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\AuthorizationCodeOAuthFlow::class => AuthorizationCodeOAuthFlowNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Link::class => LinkNormalizer::class,

        \Jane\Component\OpenApi3\JsonSchema\Model\Encoding::class => EncodingNormalizer::class,

        \Jane\Component\JsonSchemaRuntime\Reference::class => \Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\ReferenceNormalizer::class,
    ];
    protected $normalizersCache = [];

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return array_key_exists($type, $this->normalizers);
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && array_key_exists(get_class($data), $this->normalizers);
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $normalizerClass = $this->normalizers[get_class($data)];
        $normalizer = $this->getNormalizer($normalizerClass);

        return $normalizer->normalize($data, $format, $context);
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $denormalizerClass = $this->normalizers[$type];
        $denormalizer = $this->getNormalizer($denormalizerClass);

        return $denormalizer->denormalize($data, $type, $format, $context);
    }

    private function getNormalizer(string $normalizerClass)
    {
        return $this->normalizersCache[$normalizerClass] ?? $this->initNormalizer($normalizerClass);
    }

    private function initNormalizer(string $normalizerClass)
    {
        $normalizer = match ($normalizerClass) {
            OpenApiNormalizer::class => new OpenApiNormalizer(),
            ReferenceNormalizer::class => new ReferenceNormalizer(),
            InfoNormalizer::class => new InfoNormalizer(),
            ContactNormalizer::class => new ContactNormalizer(),
            LicenseNormalizer::class => new LicenseNormalizer(),
            ServerNormalizer::class => new ServerNormalizer(),
            ServerVariableNormalizer::class => new ServerVariableNormalizer(),
            ComponentsNormalizer::class => new ComponentsNormalizer(),
            SchemaNormalizer::class => new SchemaNormalizer(),
            DiscriminatorNormalizer::class => new DiscriminatorNormalizer(),
            XMLNormalizer::class => new XMLNormalizer(),
            ResponseNormalizer::class => new ResponseNormalizer(),
            MediaTypeNormalizer::class => new MediaTypeNormalizer(),
            ExampleNormalizer::class => new ExampleNormalizer(),
            HeaderNormalizer::class => new HeaderNormalizer(),
            PathItemNormalizer::class => new PathItemNormalizer(),
            OperationNormalizer::class => new OperationNormalizer(),
            ResponsesNormalizer::class => new ResponsesNormalizer(),
            TagNormalizer::class => new TagNormalizer(),
            ExternalDocumentationNormalizer::class => new ExternalDocumentationNormalizer(),
            ParameterNormalizer::class => new ParameterNormalizer(),
            RequestBodyNormalizer::class => new RequestBodyNormalizer(),
            APIKeySecuritySchemeNormalizer::class => new APIKeySecuritySchemeNormalizer(),
            HTTPSecuritySchemeNormalizer::class => new HTTPSecuritySchemeNormalizer(),
            HTTPSecuritySchemeSubNormalizer::class => new HTTPSecuritySchemeSubNormalizer(),
            OAuth2SecuritySchemeNormalizer::class => new OAuth2SecuritySchemeNormalizer(),
            OpenIdConnectSecuritySchemeNormalizer::class => new OpenIdConnectSecuritySchemeNormalizer(),
            OAuthFlowsNormalizer::class => new OAuthFlowsNormalizer(),
            ImplicitOAuthFlowNormalizer::class => new ImplicitOAuthFlowNormalizer(),
            PasswordOAuthFlowNormalizer::class => new PasswordOAuthFlowNormalizer(),
            ClientCredentialsFlowNormalizer::class => new ClientCredentialsFlowNormalizer(),
            AuthorizationCodeOAuthFlowNormalizer::class => new AuthorizationCodeOAuthFlowNormalizer(),
            LinkNormalizer::class => new LinkNormalizer(),
            EncodingNormalizer::class => new EncodingNormalizer(),
            \Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\ReferenceNormalizer::class => new \Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\ReferenceNormalizer(),
            default => throw new \InvalidArgumentException('Unknown normalizer class: ' . $normalizerClass),
        };
        if ($normalizer instanceof \Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface) {
            $normalizer->setNormalizer($this->normalizer);
        }
        if ($normalizer instanceof \Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface) {
            $normalizer->setDenormalizer($this->denormalizer);
        }
        $this->normalizersCache[$normalizerClass] = $normalizer;

        return $normalizer;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return array_combine(array_keys($this->normalizers), array_fill(0, count($this->normalizers), false));
    }
}
