<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\CheckArray;
use Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class LinkNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Jane\Component\OpenApi3\JsonSchema\Model\Link::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return $data instanceof \Jane\Component\OpenApi3\JsonSchema\Model\Link;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \Jane\Component\OpenApi3\JsonSchema\Model\Link();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref']) && !isset($data['type']) && !isset($data['properties']) && !isset($data['allOf'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        if (\array_key_exists('operationId', $data) && $data['operationId'] !== null) {
            $object->operationId = $data['operationId'];
            unset($data['operationId']);
        } elseif (\array_key_exists('operationId', $data) && $data['operationId'] === null) {
            $object->operationId = null;
            unset($data['operationId']);
        }
        if (\array_key_exists('operationRef', $data) && $data['operationRef'] !== null) {
            $object->operationRef = $data['operationRef'];
            unset($data['operationRef']);
        } elseif (\array_key_exists('operationRef', $data) && $data['operationRef'] === null) {
            $object->operationRef = null;
            unset($data['operationRef']);
        }
        if (\array_key_exists('parameters', $data) && $data['parameters'] !== null) {
            $values = new \Jane\Component\OpenApi3\JsonSchema\Runtime\JsonObject();
            foreach ($data['parameters'] as $key => $value) {
                $values[$key] = $value;
            }
            $object->parameters = $values;
            unset($data['parameters']);
        } elseif (\array_key_exists('parameters', $data) && $data['parameters'] === null) {
            $object->parameters = null;
            unset($data['parameters']);
        }
        if (\array_key_exists('requestBody', $data) && $data['requestBody'] !== null) {
            $object->requestBody = $data['requestBody'];
            unset($data['requestBody']);
        } elseif (\array_key_exists('requestBody', $data) && $data['requestBody'] === null) {
            $object->requestBody = null;
            unset($data['requestBody']);
        }
        if (\array_key_exists('description', $data) && $data['description'] !== null) {
            $object->description = $data['description'];
            unset($data['description']);
        } elseif (\array_key_exists('description', $data) && $data['description'] === null) {
            $object->description = null;
            unset($data['description']);
        }
        if (\array_key_exists('server', $data) && $data['server'] !== null) {
            $object->server = $this->denormalizer->denormalize($data['server'], \Jane\Component\OpenApi3\JsonSchema\Model\Server::class, 'json', $context);
            unset($data['server']);
        } elseif (\array_key_exists('server', $data) && $data['server'] === null) {
            $object->server = null;
            unset($data['server']);
        }
        foreach ($data as $key_1 => $value_1) {
            if (preg_match('/^x-/', (string) $key_1)) {
                $object[$key_1] = $value_1;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if (array_key_exists('operationId', get_object_vars($data)) && null !== ($data->operationId ?? null)) {
            $dataArray['operationId'] = $data->operationId ?? null;
        }
        if (array_key_exists('operationRef', get_object_vars($data)) && null !== ($data->operationRef ?? null)) {
            $dataArray['operationRef'] = $data->operationRef ?? null;
        }
        if (array_key_exists('parameters', get_object_vars($data)) && null !== ($data->parameters ?? null)) {
            $values = new \Jane\Component\OpenApi3\JsonSchema\Runtime\JsonObject();
            foreach ($data->parameters ?? null as $key => $value) {
                $values[$key] = $value;
            }
            $dataArray['parameters'] = $values;
        }
        if (array_key_exists('requestBody', get_object_vars($data)) && null !== ($data->requestBody ?? null)) {
            $dataArray['requestBody'] = $data->requestBody ?? null;
        }
        if (array_key_exists('description', get_object_vars($data)) && null !== ($data->description ?? null)) {
            $dataArray['description'] = $data->description ?? null;
        }
        if (array_key_exists('server', get_object_vars($data)) && null !== ($data->server ?? null)) {
            $dataArray['server'] = ($data->server ?? null) === null ? null : new \Jane\Component\OpenApi3\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($data->server ?? null, 'json', $context));
        }
        foreach ($data->additionalPropertyEntries() as $key_1 => $value_1) {
            if (preg_match('/^x-/', (string) $key_1)) {
                $dataArray[$key_1] = $value_1;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Jane\Component\OpenApi3\JsonSchema\Model\Link::class => false];
    }
}
