<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\CheckArray;
use Jane\Component\OpenApi3\JsonSchema\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class OAuthFlowsNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Jane\Component\OpenApi3\JsonSchema\Model\OAuthFlows::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return $data instanceof \Jane\Component\OpenApi3\JsonSchema\Model\OAuthFlows;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $object = new \Jane\Component\OpenApi3\JsonSchema\Model\OAuthFlows();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (isset($data['$ref']) && !isset($data['type']) && !isset($data['properties']) && !isset($data['allOf'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        if (\array_key_exists('implicit', $data) && $data['implicit'] !== null) {
            $object->implicit = $this->denormalizer->denormalize($data['implicit'], \Jane\Component\OpenApi3\JsonSchema\Model\ImplicitOAuthFlow::class, 'json', $context);
            unset($data['implicit']);
        } elseif (\array_key_exists('implicit', $data) && $data['implicit'] === null) {
            $object->implicit = null;
            unset($data['implicit']);
        }
        if (\array_key_exists('password', $data) && $data['password'] !== null) {
            $object->password = $this->denormalizer->denormalize($data['password'], \Jane\Component\OpenApi3\JsonSchema\Model\PasswordOAuthFlow::class, 'json', $context);
            unset($data['password']);
        } elseif (\array_key_exists('password', $data) && $data['password'] === null) {
            $object->password = null;
            unset($data['password']);
        }
        if (\array_key_exists('clientCredentials', $data) && $data['clientCredentials'] !== null) {
            $object->clientCredentials = $this->denormalizer->denormalize($data['clientCredentials'], \Jane\Component\OpenApi3\JsonSchema\Model\ClientCredentialsFlow::class, 'json', $context);
            unset($data['clientCredentials']);
        } elseif (\array_key_exists('clientCredentials', $data) && $data['clientCredentials'] === null) {
            $object->clientCredentials = null;
            unset($data['clientCredentials']);
        }
        if (\array_key_exists('authorizationCode', $data) && $data['authorizationCode'] !== null) {
            $object->authorizationCode = $this->denormalizer->denormalize($data['authorizationCode'], \Jane\Component\OpenApi3\JsonSchema\Model\AuthorizationCodeOAuthFlow::class, 'json', $context);
            unset($data['authorizationCode']);
        } elseif (\array_key_exists('authorizationCode', $data) && $data['authorizationCode'] === null) {
            $object->authorizationCode = null;
            unset($data['authorizationCode']);
        }
        foreach ($data as $key => $value) {
            if (preg_match('/^x-/', (string) $key)) {
                $object[$key] = $value;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if (array_key_exists('implicit', get_object_vars($data)) && null !== ($data->implicit ?? null)) {
            $dataArray['implicit'] = ($data->implicit ?? null) === null ? null : new \Jane\Component\OpenApi3\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($data->implicit ?? null, 'json', $context));
        }
        if (array_key_exists('password', get_object_vars($data)) && null !== ($data->password ?? null)) {
            $dataArray['password'] = ($data->password ?? null) === null ? null : new \Jane\Component\OpenApi3\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($data->password ?? null, 'json', $context));
        }
        if (array_key_exists('clientCredentials', get_object_vars($data)) && null !== ($data->clientCredentials ?? null)) {
            $dataArray['clientCredentials'] = ($data->clientCredentials ?? null) === null ? null : new \Jane\Component\OpenApi3\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($data->clientCredentials ?? null, 'json', $context));
        }
        if (array_key_exists('authorizationCode', get_object_vars($data)) && null !== ($data->authorizationCode ?? null)) {
            $dataArray['authorizationCode'] = ($data->authorizationCode ?? null) === null ? null : new \Jane\Component\OpenApi3\JsonSchema\Runtime\JsonObject($this->normalizer->normalize($data->authorizationCode ?? null, 'json', $context));
        }
        foreach ($data->additionalPropertyEntries() as $key => $value) {
            if (preg_match('/^x-/', (string) $key)) {
                $dataArray[$key] = $value;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Jane\Component\OpenApi3\JsonSchema\Model\OAuthFlows::class => false];
    }
}
