<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected;

use Jane\OpenApiRuntime\Client\Resource;
use Jane\OpenApi\Tests\Expected\Resource\TestResourceTrait;

class Client extends Resource
{
    use TestResourceTrait;
}
