<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi2\Tests\Fixtures\AllOfSchemaWithOneOfProperty\Model;

class LinkLinkBase
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string|null
     */
    protected $discriminator;

    public function getDiscriminator(): ?string
    {
        return $this->discriminator;
    }

    public function setDiscriminator(?string $discriminator)
    {
        $this->initialized['discriminator'] = true;
        $this->discriminator = $discriminator;
    }
}
