<?php

namespace PicturePark\API\Model;

class AggregationFilter extends FilterBase
{
    /**
     * @var array
     */
    protected $initialized = [];
    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The name of the aggregation this filter is connected to.
     *
     * @var string|null
     */
    protected $aggregationName;
    /**
     * The filter to be applied.
     *
     * @var mixed|null
     */
    protected $filter;
    /**
     * Autogenerated Guid at request time, for precise aggregation result mapping.
     *
     * @var string|null
     */
    protected $temporaryAggregatorRequestId;
    /**
     * The name of the aggregation this filter is connected to.
     *
     * @return string|null
     */
    public function getAggregationName(): ?string
    {
        return $this->aggregationName;
    }
    /**
     * The name of the aggregation this filter is connected to.
     *
     * @param string|null $aggregationName
     *
     * @return self
     */
    public function setAggregationName(?string $aggregationName): self
    {
        $this->initialized['aggregationName'] = true;
        $this->aggregationName = $aggregationName;
        return $this;
    }
    /**
     * The filter to be applied.
     *
     * @return mixed
     */
    public function getFilter()
    {
        return $this->filter;
    }
    /**
     * The filter to be applied.
     *
     * @param mixed $filter
     *
     * @return self
     */
    public function setFilter($filter): self
    {
        $this->initialized['filter'] = true;
        $this->filter = $filter;
        return $this;
    }
    /**
     * Autogenerated Guid at request time, for precise aggregation result mapping.
     *
     * @return string|null
     */
    public function getTemporaryAggregatorRequestId(): ?string
    {
        return $this->temporaryAggregatorRequestId;
    }
    /**
     * Autogenerated Guid at request time, for precise aggregation result mapping.
     *
     * @param string|null $temporaryAggregatorRequestId
     *
     * @return self
     */
    public function setTemporaryAggregatorRequestId(?string $temporaryAggregatorRequestId): self
    {
        $this->initialized['temporaryAggregatorRequestId'] = true;
        $this->temporaryAggregatorRequestId = $temporaryAggregatorRequestId;
        return $this;
    }
}