<?php

namespace PicturePark\API\Model;

use PicturePark\API\Runtime\AdditionalAndPatternProperties;
use PicturePark\API\Runtime\AdditionalPropertiesInterface;
class AggregationFilter extends FilterBase implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    /**
     * The name of the aggregation this filter is connected to.
     *
     * @var string|null
     */
    public ?string $aggregationName;
    /**
     * The filter to be applied.
     *
     * @var FilterBase|null
     */
    public ?FilterBase $filter;
    /**
     * Autogenerated Guid at request time, for precise aggregation result mapping.
     *
     * @var string|null
     */
    public ?string $temporaryAggregatorRequestId;
    public function definedProperties(): array
    {
        return ['aggregationName' => 'aggregationName', 'filter' => 'filter', 'temporaryAggregatorRequestId' => 'temporaryAggregatorRequestId'];
    }
}