<?php

namespace PicturePark\API\Model;

class ContentDetail
{
    /**
     * The ID of the content schema. The SchemaType of the specified schema must be Content.
     * The schema specifies the structure of the Content dictionary.
     *
     * @var string
     */
    public string $contentSchemaId;
    /**
     * An optional list of IDs of the schemas that form the layers of the content.
     * The SchemaType of the specified schemas must be Layer.
     *
     * @var list<string>|null
     */
    public ?array $layerSchemaIds;
    /**
     * All the IDs of the referenced list items (tagboxes) that do not exist in the system.
     *
     * @var list<string>|null
     */
    public ?array $brokenReferenceIds;
    /**
     * All the IDs of the indirectly referenced list items (tagboxes) that do not exist in the system.
     * They are referenced list items that reference at least a list item that do not exist in the system.
     *
     * @var list<string>|null
     */
    public ?array $brokenIndirectReferenceIds;
    /**
     * All the IDs of the contents or list items target of a relation that do not exist in the system.
     *
     * @var list<string>|null
     */
    public ?array $brokenRelationTargetIds;
    /**
     * The content data of the content. It's an object of dynamic metadata whose structure is defined in the Content schema identified.
     * by the ContentSchemaId property.
     *
     * @var array<string, mixed>|null
     */
    public ?iterable $content;
    /**
     * The metadata belonging to the layers of the content. It's a dictionary of dynamic metadata whose structure is defined in the Layer schemas identified
     * by the LayerSchemaIds property.
     *
     * @var array<string, mixed>|null
     */
    public ?iterable $metadata;
    /**
     * The content ID.
     *
     * @var string
     */
    public string $id;
    /**
     * An optional list of content permission set IDs which control content permissions. These permissions control content accessibility for the users that do not own the content.
     *
     * @var list<string>|null
     */
    public ?array $contentPermissionSetIds;
    /**
     * The Outputs generated from the content. They identifies the rendered files generated by the system.
     * They are available only for file base contents, and they depends on the output formats configured in the system.
     *
     * @var list<Output>|null
     */
    public ?array $outputs;
    /**
     * Audit information.
     *
     * @var UserAuditDetail|null
     */
    public ?UserAuditDetail $audit;
    /**
     * The owner token ID. Defines the content owner.
     *
     * @var string
     */
    public string $ownerTokenId;
    /**
     * The resolved owner.
     *
     * @var User|null
     */
    public ?User $owner;
    /**
     * Content type.
     *
     * @var string
     */
    public string $contentType;
    /**
     * Contains language specific display values. They are calculated values based on the template stored in the Content schema DisplayPatterns property.
     *
     * @var array<string, string>|null
     */
    public ?iterable $displayValues;
    /**
     * The actual lifecycle value of the content. Becomes Inactive when the content is deleted.
     *
     * @var string
     */
    public string $lifeCycle;
    /**
     * List of content rights the user has on this content
     *
     * @var list<string>|null
     */
    public ?array $contentRights;
    /**
     * Activity information: dynamically mapped from configured metadata fields or from audit information if no mapping is configured.
     *
     * @var Activity|null
     */
    public ?Activity $activity;
}