<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected\Endpoint;

class TestSimpleBodyParameter extends \Jane\OpenApiRuntime\Client\BaseEndpoint
{
    /**
     * @param string|resource|\Psr\Http\Message\StreamInterface $testString
     */
    public function __construct($testString)
    {
        $this->body = $testString;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getUri(): string
    {
        return '/test-simple';
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, \Http\Message\StreamFactory $streamFactory = null)
    {
        return [[], $this->body];
    }

    /**
     * {@inheritdoc}
     */
    public function transformResponseBody(string $body, int $status, \Symfony\Component\Serializer\SerializerInterface $serializer)
    {
        if (200 === $status) {
            return null;
        }
    }
}
