<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected\Resource;

trait TestResourceTrait
{
    /**
     * @param string $testString
     * @param string $fetch      Fetch mode to use (can be OBJECT or RESPONSE)
     *
     * @return null|\Psr\Http\Message\ResponseInterface
     */
    public function bodyParameterTriggersContentTypeBeingSet(string $testString, string $fetch = self::FETCH_OBJECT)
    {
        $endpoint = new \Jane\OpenApi\Tests\Expected\Endpoint\BodyParameterTriggersContentTypeBeingSet($testString);

        return $this->executePsr7Endpoint($endpoint, $fetch);
    }

    /**
     * @param string $fetch Fetch mode to use (can be OBJECT or RESPONSE)
     *
     * @return null|\Psr\Http\Message\ResponseInterface
     */
    public function producesTriggersAcceptBeingSet(string $fetch = self::FETCH_OBJECT)
    {
        $endpoint = new \Jane\OpenApi\Tests\Expected\Endpoint\ProducesTriggersAcceptBeingSet();

        return $this->executePsr7Endpoint($endpoint, $fetch);
    }
}
