<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Tests\Expected\Resource;

trait TestResourceTrait
{
    /**
     * @param string|resource|\Psr\Http\Message\StreamInterface $testString
     * @param string                                            $fetch      Fetch mode to use (can be OBJECT or RESPONSE)
     *
     * @return null|\Psr\Http\Message\ResponseInterface
     */
    public function testSimpleBodyParameter($testString, string $fetch = self::FETCH_OBJECT)
    {
        $endpoint = new \Jane\OpenApi\Tests\Expected\Endpoint\TestSimpleBodyParameter($testString);

        return $this->executePsr7Endpoint($endpoint, $fetch);
    }

    /**
     * @param \Jane\OpenApi\Tests\Expected\Model\Schema $testObject
     * @param string                                    $fetch      Fetch mode to use (can be OBJECT or RESPONSE)
     *
     * @return null|\Psr\Http\Message\ResponseInterface
     */
    public function testObjectBodyParameter(\Jane\OpenApi\Tests\Expected\Model\Schema $testObject, string $fetch = self::FETCH_OBJECT)
    {
        $endpoint = new \Jane\OpenApi\Tests\Expected\Endpoint\TestObjectBodyParameter($testObject);

        return $this->executePsr7Endpoint($endpoint, $fetch);
    }

    /**
     * @param array  $testObjectList
     * @param string $fetch          Fetch mode to use (can be OBJECT or RESPONSE)
     *
     * @return null|\Psr\Http\Message\ResponseInterface
     */
    public function testObjectListBodyParameter(array $testObjectList, string $fetch = self::FETCH_OBJECT)
    {
        $endpoint = new \Jane\OpenApi\Tests\Expected\Endpoint\TestObjectListBodyParameter($testObjectList);

        return $this->executePsr7Endpoint($endpoint, $fetch);
    }
}
