<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Model;

use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalAndPatternProperties;
use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalPropertiesInterface;

class ClientCredentialsFlow implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    public ?string $tokenUrl;
    public ?string $refreshUrl;
    /**
     * @var array<string, string>|null
     */
    public ?iterable $scopes;

    public function definedProperties(): array
    {
        return ['tokenUrl' => 'tokenUrl', 'refreshUrl' => 'refreshUrl', 'scopes' => 'scopes'];
    }
}
