<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Model;

class Encoding
{
    public ?string $contentType;
    /**
     * @var array<string, Header>|null
     */
    public ?iterable $headers;
    public ?string $style;
    public ?bool $explode;
    public ?bool $allowReserved = false;
}
