<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Model;

use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalAndPatternProperties;
use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalPropertiesInterface;

class Info implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    public ?string $title;
    public ?string $description;
    public ?string $termsOfService;
    public ?Contact $contact;
    public ?License $license;
    public ?string $version;

    public function definedProperties(): array
    {
        return ['title' => 'title', 'description' => 'description', 'termsOfService' => 'termsOfService', 'contact' => 'contact', 'license' => 'license', 'version' => 'version'];
    }
}
