<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Model;

use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalAndPatternProperties;
use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalPropertiesInterface;

class License implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    public ?string $name;
    public ?string $url;

    public function definedProperties(): array
    {
        return ['name' => 'name', 'url' => 'url'];
    }
}
