<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Model;

use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalAndPatternProperties;
use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalPropertiesInterface;

class RequestBody implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    public ?string $description;
    /**
     * @var array<string, MediaType>|null
     */
    public ?iterable $content;
    public ?bool $required = false;

    public function definedProperties(): array
    {
        return ['description' => 'description', 'content' => 'content', 'required' => 'required'];
    }
}
