<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\Component\OpenApi3\JsonSchema\Model;

use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalAndPatternProperties;
use Jane\Component\OpenApi3\JsonSchema\Runtime\AdditionalPropertiesInterface;

class Responses implements AdditionalPropertiesInterface
{
    use AdditionalAndPatternProperties;
    /**
     * @var Response|Reference|null
     */
    public $default;

    public function definedProperties(): array
    {
        return ['default' => 'default'];
    }
}
