name: CI
on:
  push:
    branches:
      - next
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'mkdocs.yaml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'LICENSE'
      - '.editorconfig'
      - '.gitattributes'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'mkdocs.yaml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'LICENSE'
      - '.editorconfig'
      - '.gitattributes'
      - '.github/ISSUE_TEMPLATE/**'
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: castor-php/setup-castor@v0.1.0
      - name: 'php-cs-fixer check'
        run: 'castor qa:cs:check'
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: 8.4
          coverage: none
      - name: composer install
        run: composer update --prefer-stable
      - name: setup
        uses: castor-php/setup-castor@v0.1.0
      - name: 'phpstan check'
        run: 'castor qa:phpstan'
  phpstan-generated:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: 8.4
          coverage: none
      - name: composer install
        run: composer update --prefer-stable
      - name: setup
        uses: castor-php/setup-castor@v0.1.0
      - name: 'phpstan check on generated code'
        run: 'castor qa:phpstan:generated'
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        php-versions:  ['8.1', '8.2', '8.3', '8.4']
        symfony-require: ['']
        include:
          - php-versions: '8.4'
            symfony-require: '6.4.*'
          - php-versions: '8.4'
            symfony-require: '7.0.*'
          - php-versions: '8.4'
            symfony-require: '7.1.*'
          - php-versions: '8.4'
            symfony-require: '7.2.*'
          - php-versions: '8.4'
            symfony-require: '7.3.*'
          - php-versions: '8.4'
            symfony-require: '7.4.*'
          - php-versions: '8.4'
            symfony-require: '8.0.*'
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-require }}
    name: tests-${{ matrix.php-versions }} - SF ${{ matrix.symfony-require }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-${{ matrix.php-versions }}-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, json, intl, dom
      # We need Flex to enforce Symfony version with `SYMFONY_REQUIRE` env var
      - name: Install Symfony Flex
        run: composer global require --no-progress --no-scripts --no-plugins symfony/flex
      - name: Enable Symfony Flex
        run: composer global config --no-plugins allow-plugins.symfony/flex true
      - name: composer install
        run: composer update --prefer-dist --no-interaction --no-ansi
      - name: install node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: install prism
        run: yarn global add @stoplight/prism-cli
      - name: run OpenApi3 prism server
        run: nohup prism mock src/Component/OpenApi3/Tests/client/openapi.yaml -p 4010 &
      - name: run OpenApi2 prism server
        run: nohup prism mock src/Component/OpenApi2/Tests/client/swagger.yaml -p 4011 &
      - name: run OpenApi31 prism server
        run: nohup prism mock src/Component/OpenApi31/Tests/client/openapi.yaml -p 4012 &
      - name: tests
        run: vendor/bin/phpunit --exclude-group none
  tests-lowest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer-lowest
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-lowest-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: 8.1
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-lowest --prefer-stable
      - name: install node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: install prism
        run: yarn global add @stoplight/prism-cli
      - name: run OpenApi3 prism server
        run: nohup prism mock src/Component/OpenApi3/Tests/client/openapi.yaml -p 4010 &
      - name: run OpenApi2 prism server
        run: nohup prism mock src/Component/OpenApi2/Tests/client/swagger.yaml -p 4011 &
      - name: run OpenApi31 prism server
        run: nohup prism mock src/Component/OpenApi31/Tests/client/openapi.yaml -p 4012 &
      - name: tests
        run: vendor/bin/phpunit --exclude-group none
