name: CI
on:
  push:
    branches:
      - next
  pull_request: ~
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: 8.4
          coverage: none
      - name: install PHP CS Fixer
        run: 'composer install -n --prefer-dist --optimize-autoloader --working-dir=tools/php-cs-fixer'
      - name: 'php-cs-fixer check'
        run: 'PHP_CS_FIXER_IGNORE_ENV=1 tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff'
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: 8.4
          coverage: none
      - name: install PHPStan
        run: 'composer install -n --prefer-dist --optimize-autoloader --working-dir=tools/phpstan'
      - name: composer install
        run: composer update --prefer-stable
      - name: 'phpstan check'
        run: 'tools/phpstan/vendor/bin/phpstan analyse --configuration=tools/phpstan/phpstan.neon'
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        php-versions:  ['8.1', '8.2', '8.3', '8.4']
        symfony-require: ['']
        include:
          - php-versions: '8.4'
            symfony-require: '6.4'
          - php-versions: '8.4'
            symfony-require: '7.0'
          - php-versions: '8.4'
            symfony-require: '7.1'
          - php-versions: '8.4'
            symfony-require: '7.2'
          - php-versions: '8.4'
            symfony-require: '7.3'
          - php-versions: '8.4'
            symfony-require: '7.4'
          - php-versions: '8.4'
            symfony-require: '8.0'
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-require }}
    name: tests-${{ matrix.php-versions }} - SF ${{ matrix.symfony-require }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-${{ matrix.php-versions }}-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, json, intl, dom
      # We need Flex to enforce Symfony version with `SYMFONY_REQUIRE` env var
      - name: Install Symfony Flex
        run: composer global require --no-progress --no-scripts --no-plugins symfony/flex
      - name: Enable Symfony Flex
        run: composer global config --no-plugins allow-plugins.symfony/flex true
      - name: composer install
        run: composer update --prefer-dist --no-interaction --no-ansi
      - name: install prism
        run: curl -L https://raw.githack.com/stoplightio/prism/master/install | sh
      - name: run OpenApi3 prism server
        run: nohup prism mock src/Component/OpenApi3/Tests/client/openapi.yaml -p 4010 &
      - name: run OpenApi2 prism server
        run: nohup prism mock src/Component/OpenApi2/Tests/client/swagger.yaml -p 4011 &
      - name: tests
        run: vendor/bin/phpunit --exclude-group none
  tests-lowest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer-lowest
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-lowest-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: 8.1
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-lowest --prefer-stable
      - name: install prism
        run: curl -L https://raw.githack.com/stoplightio/prism/master/install | sh
      - name: run OpenApi3 prism server
        run: nohup prism mock src/Component/OpenApi3/Tests/client/openapi.yaml -p 4010 &
      - name: run OpenApi2 prism server
        run: nohup prism mock src/Component/OpenApi2/Tests/client/swagger.yaml -p 4011 &
      - name: tests
        run: vendor/bin/phpunit --exclude-group none
