name: CI
on:
  push:
    branches:
      - next
  pull_request: ~
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: 8.4
          coverage: none
      - name: install PHP CS Fixer
        run: 'composer install -n --prefer-dist --optimize-autoloader --working-dir=tools/php-cs-fixer'
      - name: 'php-cs-fixer check'
        run: 'PHP_CS_FIXER_IGNORE_ENV=1 tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff'
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: 8.4
          coverage: none
      - name: install PHPStan
        run: 'composer install -n --prefer-dist --optimize-autoloader --working-dir=tools/phpstan'
      - name: composer install
        run: composer update --prefer-stable
      - name: 'phpstan check'
        run: 'tools/phpstan/vendor/bin/phpstan analyse --configuration=tools/phpstan/phpstan.neon'
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-version:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
        symfony-version:
          - 6.4.*
          - 7.0.*
        dependencies:
          - ""
        include:
          - php-version: 8.1
            dependencies: --prefer-lowest
            symfony-version: 6.4.*
    env:
      SYMFONY_DEPRECATIONS_HELPER: max[self]=0
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
    name: tests / PHP ${{ matrix.php-version }} / Symfony ${{ matrix.symfony-version }} / ${{ matrix.dependencies != '' && 'Highest deps' || 'Lowest deps' }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/
          key: composer-${{ matrix.php-version }}-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update ${{ matrix.dependencies }} --prefer-stable
      - name: install prism
        run: curl -L https://raw.githack.com/stoplightio/prism/master/install | sh
      - name: run OpenApi3 prism server
        run: nohup prism mock src/Component/OpenApi3/Tests/client/openapi.yaml -p 4010 &
      - name: run OpenApi2 prism server
        run: nohup prism mock src/Component/OpenApi2/Tests/client/swagger.yaml -p 4011 &
      - name: tests
        run: vendor/bin/phpunit --exclude-group none
