<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Jane\OpenApi\Model;

class Operation extends \ArrayObject
{
    /**
     * @var string[]
     */
    protected $tags;
    /**
     * A brief summary of the operation.
     *
     * @var string
     */
    protected $summary;
    /**
     * A longer description of the operation, GitHub Flavored Markdown is allowed.
     *
     * @var string
     */
    protected $description;
    /**
     * information about external documentation.
     *
     * @var ExternalDocs
     */
    protected $externalDocs;
    /**
     * A unique identifier of the operation.
     *
     * @var string
     */
    protected $operationId;
    /**
     * @var string[]
     */
    protected $produces;
    /**
     * @var string[]
     */
    protected $consumes;
    /**
     * The parameters needed to send a valid API call.
     *
     * @var BodyParameter[]|HeaderParameterSubSchema[]|FormDataParameterSubSchema[]|QueryParameterSubSchema[]|PathParameterSubSchema[]|JsonReference[]
     */
    protected $parameters;
    /**
     * Response objects names can either be any valid HTTP status code or 'default'.
     *
     * @var Response|JsonReference[]|mixed[]
     */
    protected $responses;
    /**
     * The transfer protocol of the API.
     *
     * @var string[]
     */
    protected $schemes;
    /**
     * @var bool
     */
    protected $deprecated;
    /**
     * @var string[][][]
     */
    protected $security;

    /**
     * @return string[]
     */
    public function getTags(): ?array
    {
        return $this->tags;
    }

    /**
     * @param string[] $tags
     *
     * @return self
     */
    public function setTags(?array $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * A brief summary of the operation.
     *
     * @return string
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * A brief summary of the operation.
     *
     * @param string $summary
     *
     * @return self
     */
    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    /**
     * A longer description of the operation, GitHub Flavored Markdown is allowed.
     *
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * A longer description of the operation, GitHub Flavored Markdown is allowed.
     *
     * @param string $description
     *
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * information about external documentation.
     *
     * @return ExternalDocs
     */
    public function getExternalDocs(): ?ExternalDocs
    {
        return $this->externalDocs;
    }

    /**
     * information about external documentation.
     *
     * @param ExternalDocs $externalDocs
     *
     * @return self
     */
    public function setExternalDocs(?ExternalDocs $externalDocs): self
    {
        $this->externalDocs = $externalDocs;

        return $this;
    }

    /**
     * A unique identifier of the operation.
     *
     * @return string
     */
    public function getOperationId(): ?string
    {
        return $this->operationId;
    }

    /**
     * A unique identifier of the operation.
     *
     * @param string $operationId
     *
     * @return self
     */
    public function setOperationId(?string $operationId): self
    {
        $this->operationId = $operationId;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getProduces(): ?array
    {
        return $this->produces;
    }

    /**
     * @param string[] $produces
     *
     * @return self
     */
    public function setProduces(?array $produces): self
    {
        $this->produces = $produces;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getConsumes(): ?array
    {
        return $this->consumes;
    }

    /**
     * @param string[] $consumes
     *
     * @return self
     */
    public function setConsumes(?array $consumes): self
    {
        $this->consumes = $consumes;

        return $this;
    }

    /**
     * The parameters needed to send a valid API call.
     *
     * @return BodyParameter[]|HeaderParameterSubSchema[]|FormDataParameterSubSchema[]|QueryParameterSubSchema[]|PathParameterSubSchema[]|JsonReference[]
     */
    public function getParameters(): ?array
    {
        return $this->parameters;
    }

    /**
     * The parameters needed to send a valid API call.
     *
     * @param BodyParameter[]|HeaderParameterSubSchema[]|FormDataParameterSubSchema[]|QueryParameterSubSchema[]|PathParameterSubSchema[]|JsonReference[] $parameters
     *
     * @return self
     */
    public function setParameters(?array $parameters): self
    {
        $this->parameters = $parameters;

        return $this;
    }

    /**
     * Response objects names can either be any valid HTTP status code or 'default'.
     *
     * @return Response|JsonReference[]|mixed[]
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * Response objects names can either be any valid HTTP status code or 'default'.
     *
     * @param Response|JsonReference[]|mixed[] $responses
     *
     * @return self
     */
    public function setResponses($responses): self
    {
        $this->responses = $responses;

        return $this;
    }

    /**
     * The transfer protocol of the API.
     *
     * @return string[]
     */
    public function getSchemes(): ?array
    {
        return $this->schemes;
    }

    /**
     * The transfer protocol of the API.
     *
     * @param string[] $schemes
     *
     * @return self
     */
    public function setSchemes(?array $schemes): self
    {
        $this->schemes = $schemes;

        return $this;
    }

    /**
     * @return bool
     */
    public function getDeprecated(): ?bool
    {
        return $this->deprecated;
    }

    /**
     * @param bool $deprecated
     *
     * @return self
     */
    public function setDeprecated(?bool $deprecated): self
    {
        $this->deprecated = $deprecated;

        return $this;
    }

    /**
     * @return string[][][]
     */
    public function getSecurity(): ?array
    {
        return $this->security;
    }

    /**
     * @param string[][][] $security
     *
     * @return self
     */
    public function setSecurity(?array $security): self
    {
        $this->security = $security;

        return $this;
    }
}
